### ISSUE TITLE
Error when deleted product with photo

### ISSUE THREAD

**Issue by dieunb** [josegonzalez/cakephp-upload#102]
I added a product and review photo. But, when i delete it, it show error. How to fix it, please?

Notice (8): Undefined index: resume [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1256]
Code Context
UploadBehavior::_prepareFilesForDeletion() - APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1256
UploadBehavior::beforeDelete() - APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 324
ObjectCollection::trigger() - CORE/Cake/Utility/ObjectCollection.php, line 131
call_user_func - [internal], line ??
CakeEventManager::dispatch() - CORE/Cake/Event/CakeEventManager.php, line 247
Model::delete() - CORE/Cake/Model/Model.php, line 2389
ProductsController::admin_delete() - APP/Controller/ProductsController.php, line 101
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 485
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 186
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 161
[main] - APP/webroot/index.php, line 97

**Comment by davidyell** [comment]
Closing this ticket as it's a year old now.
