### ISSUE TITLE
Can't save thumbnail

### ISSUE THREAD

**Issue by eru** [josegonzalez/cakephp-upload#105]
public $actsAs = array(
        'Upload.Upload' => array(
            'photo' => array(
                'deleteOnUpdate' => true,
                'thumbnails' => true,
                'thumbnailSizes' => array(
                    'thumb' => '100x100',
                ),  
                'thumbnailName' => 'thumb',
                'thumbnailType' => 'png',
            ),  
        ),  
    );

If you do upload the same ID again, because the old ones are deleted after thumbnail generation, the generated thumbnails will be deleted.

**Comment by josegonzalez** [comment]
Closing as there hasn't been movement on this in months. Please comment if you are still having this issue.
