### ISSUE TITLE
Upload not working for update with the same file name

### ISSUE THREAD

**Issue by muhammadcahya** [josegonzalez/cakephp-upload#118]
Hello, The upload is working well for insert and update. But sometimes I upload with the same file (name), in the previous insert/update. The upload is not working :( <br>
The file name is add to database, but the old image file is deleted.

**Comment by davidyell** [comment]
Related to #143

**Comment by josegonzalez** [comment]
Closing as there hasn't been movement on this in months. Please comment if you are still having this issue.
