### ISSUE TITLE
Polymorphic documentation may be incorrect?

### ISSUE THREAD

**Issue by imszone** [josegonzalez/cakephp-upload#127]
Hi, 

I tried to follow the Polymorphic instructions and I am getting the following error when I try to list my users:

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Attachment.model' in 'where clause'

SQL Query: SELECT `Image`.`id`, `Image`.`model`, `Image`.`foreign_key`, `Image`.`name`, `Image`.`attachment`, `Image`.`dir`, `Image`.`type`, `Image`.`size`, `Image`.`active` FROM `joseph2`.`attachments` AS `Image` WHERE `Attachment`.`model` = 'User' AND `Image`.`foreign_key` IN (1, 3, 20, 21, 22, 23, 24) 

This is the relation:
```php
public $hasMany = array(
        'Image' => array(
            'className' => 'Attachment',
            'foreignKey' => 'foreign_key',
            'conditions' => array(
                'Attachment.model' => 'User',
            ),
        ),
    ); 
```
So, if I change the conditions to:
```php
public $hasMany = array(
        'Image' => array(
            'className' => 'Attachment',
            'foreignKey' => 'foreign_key',
            'conditions' => array(
                //'Attachment.model' => 'User',
                'Image.model' => 'User',
            ),
        ),
    ); 
```
It lists my users just fine, but no record is saved in the Attachment database when I try to create a new user with an image. Of course, I will be adding more images and files related to the user when I get this working :)  I just want to have it rolling for now in the simplest way.

Am I truly missing something, or is the documentation ?

**Comment by davidyell** [comment]
Closing this as it's two years old now.
