### ISSUE TITLE
Why when I update a file that has the same name does not work?

### ISSUE THREAD

**Issue by vnt** [josegonzalez/cakephp-upload#143]
Why when I update a file that has the same name does not work?

these are the settings:
	'thumbnailMethod' => 'php',
		'thumbnailQuality' => 85,
		'thumbnailSizes' => array(),
		'thumbnailType' => false,
		'deleteOnUpdate' => true,
		'mediaThumbnailType' => 'png',
		'saveDir' => true,
		'deleteFolderOnDelete' => true,
		'mode' => 0777,

**Comment by josegonzalez** [comment]
Closing as there hasn't been movement on this in months. Please comment if you are still having this issue.
