### ISSUE TITLE
Polymorphic Example Not working

### ISSUE THREAD

**Issue by zihatzik** [josegonzalez/cakephp-upload#150]
Hi there.
I did everything like your example but i didnt manage to make it work.
This post could not be saved. Please try again.
Is that the correct structure of the array? 

    Array
    (
        [Image] => Array
            (
                [0] => Array
                    (
                        [model] => PropertyGroup
                        [attachment] => Array
                            (
                                [name] => zinwn-01.jpg
                                [type] => image/jpeg
                                [tmp_name] => C:\xampp\tmp\php6F.tmp
                                [error] => 0
                                [size] => 71437
                            )

                    )

            )

    )

Is it because iam using xamp?

**Comment by josegonzalez** [comment]
Closing as there hasn't been movement on this in months. Please comment if you are still having this issue.
