### ISSUE TITLE
Runtime is empty

### ISSUE THREAD

**Issue by balaji5686** [josegonzalez/cakephp-upload#170]
Hi 

$this->runtime[$model->alias][$field])
it is empty so its not creating a temp folder 
Can you help me ??

**Comment by julio6114** [comment]
I've got same problem but I've got
$this->Form->create('News', array('type' => 'file'));

**Comment by josegonzalez** [comment]
Your field needs to be of type file as well.

**Comment by julio6114** [comment]
yes I do that : 
		echo $this->Form->input('photo', array('type' => 'file'));

**Comment by davidyell** [comment]
Try re-reading the basic example and checking through your code.

http://cakephp-upload.readthedocs.org/en/latest/examples.html#basic-example

Ensure the plugin is loaded, the behaviour is attached and to the correct model, double check your form code, make sure you're in the right action in your browser, and also that you've included the 'dir' field in your form.

**Comment by julio6114** [comment]
I find!!

I've got an other behavior before Upload.Upload.
I do behavior Upload at first of array 'actAs' and it's works

Thank you!
