### ISSUE TITLE
how to upload multiple files ??

### ISSUE THREAD

**Issue by divyanshu-das** [josegonzalez/cakephp-upload#172]
I want to upload multiple images.
This is my Photo model:-

    public $actsAs = array(
      'Upload.Upload' => array(
        'image' => array(
          'fields' => array(
            'dir' => 'dir'
          ),
        'thumbnailSizes' => array(
            'xvga' => '1024x768',
            'vga' => '149x178',
            'thumb' => '150x150',
          ),
          'thumbnailMethod' => 'php'
        )
      )
    );

This is the upload form:-

    <?php
    echo $this->Form->create('Photo', array('type' => 'file'));
    echo $this->Form->input('image', array('type' => 'file', 'multiple' => true));
    echo $this->Form->input('dir', array('type' => 'hidden'));
    echo $this->Form->submit(__('Submit'));
    echo $this->Form->end();
    ?>

And controller code:-

    public function add_photos() {
      if ($this->request->is('post')) {
        // pr($this->request->data); die;
        $this->Photo->create();
        if ($this->Photo->saveAll($this->request->data)) {
          $this->Session->setFlash(__('Images saved successfully'));
          $this->redirect(array('action' => 'success'));
        } else {
          $this->Session->setFlash(__('Upload not sucessfull'));
        }
      }
    }

I am only able to upload one image. 
Can someone help me out here ??

**Comment by wanderarce** [comment]
Não funcionou, segui seu tutorial mas só realiza o Upload de uma imagem somente.

**Comment by sonidivyek87** [comment]
Hello, Thank you sir, This plugin works excellent for me, but when I have multiple file upload-> select 30 images (approx 15 MB) -> Upload only 18-20 images.
Please help if anyone can, Thank you in advance.

**Comment by josegonzalez** [comment]
Its definitely a problem with your memory limits. You'll want to handle uploads differently, and thats not a bug with this plugin.
