### ISSUE TITLE
having problem with saving multiple files

### ISSUE THREAD

**Issue by kishon** [josegonzalez/cakephp-upload#182]
While trying to save multiple images, the 'photo' column has value as NULL and also don't see anything in the directory. The data that is fed into saveAll method is below.

```
    'photo' => array(
        (int) 0 => array(
            'name' => 'Screenshot at 2012-04-27 17:53:29.png',
            'type' => 'image/png',
            'tmp_name' => '/tmp/phpqyZuMI',
            'error' => (int) 0,
            'size' => (int) 825659
        ),
        (int) 1 => array(
            'name' => 'Screenshot from 2012-10-30 18:41:48.png',
            'type' => 'image/png',
            'tmp_name' => '/tmp/phpclnsnM',
            'error' => (int) 0,
            'size' => (int) 300070
        )
    )
```

I'd like to know how 'photo' will be added in database table when there are multiple files. Will it create a new row for every file?

**Comment by vnt** [comment]
I tried the example of Manfed, and it works.
I wanted to ask if you can add it to the guide and if you can put an example of validation for the field documents.
Thanks a lot.
