### ISSUE TITLE
Allow only certain extensions for upload.

### ISSUE THREAD

**Issue by nizam27391** [josegonzalez/cakephp-upload#190]
Hi. 
I'm new to this plugin but it is an awesome plugin.
My problem is that I cannot limit the extensions for certain file upload. I already have the following code but didn't work. Didn't know if this one is correct or not.

Kindly teach me if there is anything wrong.
Thanx

```
     public $actsAs = array(
    'Upload.Upload' => array(
            'photo'=> array(
                    'pathMethod'=>'flat',
                    'path'=> '{ROOT}webroot{DS}files{DS}photo{DS}',
                    'extensions'=>array('bmp', 'png', 'jpg'),
                )
        )
    );

public $validate = array(
        'rule' => array('isValidExtension', array('bmp', 'png', 'jpg'),false),
        'message' => 'File does not have a valid extension'
    );
```

**Comment by PhantomWatson** [comment]
Is `isValidExtension()` a method that used to be in this plugin? It doesn't seem to be in the code and I can't find it in the commit history. Am I overlooking it, or is there an alternative that we should be using instead?

**Comment by PhantomWatson** [comment]
Was `isValidExtension()` phased out in favor of CakePHP's [core `extension()` validation rule](http://api.cakephp.org/3.0/class-Cake.Validation.Validation.html#_extension)?

**Comment by josegonzalez** [comment]
Yes
