### ISSUE TITLE
Polymorphic Deletion includes errors

### ISSUE THREAD

**Issue by loganbest** [josegonzalez/cakephp-upload#200]
Hello,
I have setup polymorphic uploading and so far it works great. I'm running into an odd issue when deleting though. I'm using the standard "http://example.com/admin/documents/delete/25" to delete a record, it's associated asset record and it's file.

app/Model/Document.php
```php
        public $hasOne = array(
                'Asset' => array(
                        'className' => 'Asset',
                        'foreignKey' => 'foreign_id',
                        'conditions' => array('Asset.class' => 'Document'),
                        'dependent' => true
                ),
        );
```
app/Model/Asset.php
```php
        public $actsAs = array(
                'Upload.Upload' => array(
                        'Document' => array(
                                'pathMethod' => 'flat',
                                'path' => '{ROOT}webroot{DS}uploads{DS}documents{DS}',
                                'fields' => array('dir' => 'dir', 'type' => 'ext', 'size' => 'size'),
                                'extensions' => array('pdf','doc','docx','xls','xlsx'),
                                'thumbnails' => false
                        ),
                        'Menu' => array(
                                'pathMethod' => 'flat',
                                'path' => '{ROOT}webroot{DS}uploads{DS}menus{DS}',
                                'fields' => array('dir' => 'dir', 'type' => 'ext', 'size' => 'size'),
                                'extensions' => array('jpg','jpeg','png','gif','tif','tiff'),
                                'thumbnailQuality' => 100,
                                'thumbnailSizes' => array(
                                        'big' => '253x402',
                                ),
                                'thumbnailPrefixStyle' => false
                        ),
                        'Image' => array(
                                'pathMethod' => 'flat',
                                'path' => '{ROOT}webroot{DS}uploads{DS}images{DS}',
                                'fields' => array('dir' => 'dir', 'type' => 'ext', 'size' => 'size'),
                                'extensions' => array('jpg','jpeg','png','gif','tif','tiff'),
                                'thumbnailQuality' => 100,
                                'thumbnailSizes' => array(
                                        'big' => '341x225',
                                ),
                                'thumbnailPrefixStyle' => false
                        ), ......
```
When I go to delete a document record (using the completely vanilla admin_delete method which should work just fine) I get the following errors. 

```
Notice (8): Undefined index: Document [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Menu [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Image [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: VideoScreen [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Video [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Sidebar [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Slideshow [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Setting [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Home [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: Map [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: MapList [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]

Notice (8): Undefined index: News [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1646]
```
Even though those errors return the document record and asset record are deleted, but the file itself is not. What can be done to fix it?

**Comment by wanderarce** [comment]
Warning (2): rename(,C:\xampp\htdocs\maestro\app\webroot\img\archive\2\Sleep Away.mp3): Invalid argument [APP\Plugin\Upload\Model\Behavior\UploadBehavior.php, line 385]


public $actsAs = array('Auditable.Auditable',
        'Upload.Upload' => array(
            'image' => array(
                'fields' => array(
                    'dir' => 'image_dir'
                ),
                'rule'=>array('isValidMimeType', array('image/png','image/jpg','image/jpeg')),
                'message' => 'File is not a pdf or png',
                'thumbnailSizes' => array(
                    'big' => '639x423',
                    'small' => '130x130',
                    'thumb' => '90x82'
                    
                ),
                'thumbnailMethod' => 'php',
                //necessario informar o path para que seja salvo corretamente.
                'path' => '{ROOT}webroot{DS}img{DS}{field}{DS}',
                'deleteOnUpdate' => true
            ),
            'archive' => array(
                'fields' => array(
                    'dir' => 'archive_dir'
                ),
                'extensions' => array('pdf','doc','docx','xls','xlsx','mp3'),
                'message' => 'File is not a pdf or mp3',
                //'thumbnailMethod' => 'php',
                //necessario informar o path para que seja salvo corretamente.
                'path' => '{ROOT}webroot{DS}img{DS}{field}{DS}',
                'deleteOnUpdate' => true
            )
        )
    );
não está realizando uploads de mp3 e documentos com espaços

**Comment by josegonzalez** [comment]
@wanderarce that is not related to this issue.
