### ISSUE TITLE
How do I save a base64 encoded image?

### ISSUE THREAD

**Issue by mallendeo** [josegonzalez/cakephp-upload#202]
Hi, I have an ajax form which uses the webcam (getUserMedia) to take a photo, and then I get the base64 code of png from the canvas. I'm using this plugin for everything else that don't use  getUserMedia (simple input upload).

How can I make this work with your plugin?
Thanks :)

**Comment by kousei** [comment]
hai. I try below and work well with this plugin
      //target file before decode
      $img = Hash::get($this->request->data,"User.photo");

      $img = explode(',', $img);
      $start = strlen('data:image/');

      //to get filetype [0] => data:image/jpeg;base64
      $mystring = $img[0];
      //to get filetype
      $findme = ';';
      $end = strpos($mystring, $findme);
      $fileType = substr($img[0], $start, $end - $start);
      //decode it
      $data = base64_decode($img[1]);
      
      $filename = 'profile.' . $fileType;
      $file_dir = WWW_ROOT . DS. 'files' .DS. 'user' .DS. 'photo' .DS. $filename;
      //file create
      file_put_contents($file_dir, $data);
      
      //not necessarily. I write it for use delete function this plugin
      $filesize = filesize($file_dir);

      //after base64 decode ,file delete
      $this->request->data['User']['photo'] = null;

      $this->request->data['User']['photo']['name'] = $filename;
      $this->request->data['User']['photo']['type'] = 'image/' . $fileType;
      $this->request->data['User']['photo']['tmp_name'] = $file_dir;
      $this->request->data['User']['photo']['error'] = 0;
      $this->request->data['User']['photo']['size'] = $filesize;
      $this->User->save($this->request->data)
