### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Column 'Array' unknown in 'field list'

### ISSUE THREAD

**Issue by chromosplanet** [josegonzalez/cakephp-upload#207]
Im having an issue with my remote application when I upload multiples images.
In my localhost works perfectly.

The data that is being sent:

```
array(4) {
  ["Image"]=> array(12) {
    [0] => array(4) {
      ["id"] => string(3) "664"
      ["veiculo_id"] => string(3) "664"
      ["attachment"] => array(5) {
        ["name"] => string(0) ""
        ["type"] => string(0) ""
        ["tmp_name"] => string(0) ""
        ["error"] => int(4)
        ["size"] => int(0)
      }
      ["model"] => string(4) "Post"
    }
    [1] => array(4) {
      ["id"] => string(3) "665"
      ["veiculo_id"] => string(3) "665"
      ["attachment"] => array(5) {
        ["name"] => string(0) ""
        ["type"] => string(0) ""
        ["tmp_name"] => string(0) ""
        ["error"] => int(4)
        ["size"] => int(0)
      }
      ["model"] => string(4) "Post"
    }
  }
```

**Comment by bouzakher** [comment]
Bonjour josegonzalez/cakephp,

J&#39;aimerais vous inviter à rejoindre mon réseau professionnel sur LinkedIn.

Bilel

Accepter : http://www.linkedin.com/blink?simpleRedirect=0OcjcPdPsRe38Nd3AUdzsVdPARfkh9rCZFt65QqnpKqipptnxVdQtCj3RVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CYObmFRcTkVujpFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=


Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à nos utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : http://www.linkedin.com/blink?simpleRedirect=rP8JqDkPtjBVdCAJpjlzem4RfmhFpipTcSRqj55UrBd5kDAMpmxvqjB6iTkPqmZUuDhIt6dnsQ5GkSITcl1UjT5WrBcRi6NNlkNLnPtfl3ladkRyu2RdoQd5kORkcnhWtB9jinp7rm5zikRedPlqbml9iAoTem5Isn9Le5tGdngSu7dxkPtajBZ5d4Fhe74QgBZ5rm51pAYNcBhRhmdVgzB2kRpgrTxSlk51gk5dtkxxqQgRh4cNhB51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CYObmFRcTkVujpFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5979768959900090368_500&amp;markAsRead=This email was intended for josegonzalez/cakephp josegonzalez/cakephp-upload. Learn why we included this at the following link: http://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CYObmFRcTkVujpFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by davidyell** [comment]
<Spam removed>

**Comment by josegonzalez** [comment]
For real?

**Comment by bouzakher** [comment]
Bilel Bouzakher souhaite rejoindre votre réseau sur LinkedIn. Que souhaitez-vous répondre ?

Accepter : http://www.linkedin.com/blink?simpleRedirect=0OcjcPdPsRe38Nd3AUdzsVdPARfkh9rCZFt65QqnpKqipptnxVdQtCj3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9z4QbnhQq68McPtFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Voir le profil de Bilel Bouzakher : http://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9z4QbnhQq68McPtFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Vous recevez des e-mails de rappel concernant vos invitations en attente. Se désabonner ici : http://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kQejwUej4Tbm4MoPwTc3wMoztycP5AdzkOdPgRd6lyemkPpjwPe3ASdjsOp64Nej0JdP0Mdj8McPcJqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8NcPcTdPkUcz4QejwSdPATejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9z4QbnhQq68McPtFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à nos utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : http://www.linkedin.com/blink?simpleRedirect=0Nd2RQt6xyc3cTqiRBdmcVojkZp6BB9ABQu39OhC4Pq4ZahmpTnQd6i3ANrCQMjntBhmNPpC5SqloNpnpphSRqtk9LtQ8SckpEk7pCsD4Ok5lqjApQcTcSoTcNhnFys4lzp51BcAhdp4Z6kCVHeldymCBjkmUSmjoNpmITtm9aj7lJdB9HlRt8pjlldllPukgOq5x9sSlvdRh6s7BVq3oNrmNdiSxPgTtlgk51kj1NpSxegQ9NhSJ7kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9z4QbnhQq68McPtFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5979768959900090368_500&amp;markAsRead= Découvrez pourquoi nous avons inclus ceci en suivant ce lien : http://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9z4QbnhQq68McPtFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct., Mountain View, CA 94043, USA.

**Comment by bouzakher** [comment]
Bilel Bouzakher souhaite rejoindre votre réseau sur LinkedIn. Que souhaitez-vous répondre ?

Accepter : https://www.linkedin.com/blink?simpleRedirect=0OcjcPdPsRe38Nd3AUdzsVdPARfkh9rCZFt65QqnpKqipptnxVdQtCj3RVpkJApn9xq7cCej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9DAObmdIunFNoztFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Voir le profil de Bilel Bouzakher : https://www.linkedin.com/blink?simpleRedirect=ej5vs7xBnTpKqjRHpipOpmhKqmRBsyRQs6lzoS4JoyRDtCVFnSRJrScJr6RBfmtKqmJzon9Q9DpMrzRQ9DAObmdIunFNoztFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Vous recevez des e-mails de rappel concernant vos invitations en attente. Se désabonner ici : https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kQejwUej4Tbm4MoPwTc3wMoztycP5AdzkOdPgRd6lyemkPpjwPe3ASdjsOp64Nej0JdP0Mdj8McPcJqk8O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z8NcPcTdPkUcz4QejwSdPATejkZp6BD9zANnT1UplZSrCAZqSkCoDlPrDkJpyRzoClJnSRJrScJr6RBfmtKqmJzon9Q9CZLpPRQ9DAObmdIunFNoztFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=

Vous avez reçu une invitation à rejoindre un réseau. LinkedIn utilise votre adresse e-mail pour faire des suggestions à nos utilisateurs dans des fonctionnalités telles que Les connaissez-vous ? Se désabonner ici : https://www.linkedin.com/blink?simpleRedirect=1VcyRzr7BWsm8TqiRBdmcVojkZp6BB9z1xm65Su6RKkPkVjkpNcCJ8qnEMnTxotnpvrD5eq4JolThhcBlpkTdEm7BBu4VHu71lr5xFejdvsSQJrn5Mt48SsiRVm59Wq4NTjQBymz4NpmBce3tzk4dSpQlek5AVr6Vgj6Bacmp5szhGr2Rqm6tOgSxjgk54q6ZOq31joPxommx8qmVgt50QbkhUuDtdqntlgk51gmlqt6pEtktTjBt6kk4Zp6BLr2oVclZMu6lvtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DAObmdIunFNoztFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5979768959900090368_500&amp;markAsRead= Découvrez pourquoi nous avons inclus ceci en suivant ce lien : https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioVclZMu6lvtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DAObmdIunFNoztFbmkRoPBxdjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5979768959900090368_500&markAsRead=
&copy; 2014, LinkedIn Corporation. 2029 Stierlin Ct., Mountain View, CA 94043, USA.

**Comment by davidyell** [comment]
Locked to prevent spam.
