### ISSUE TITLE
delete whole directory suddenly

### ISSUE THREAD

**Issue by mobasher92** [josegonzalez/cakephp-upload#212]
i am using this plugin and it work fine but suddenly it deletes the whole directory
for example i have an image table the picture field is called photo so the directory will be image/photo/ids..
the users upload images and it is fine but suddenly it deletes all the directories in image/photo !
why is this happening. i am sure there is enough space in the host

**Comment by josegonzalez** [comment]
Closing as there hasn't been movement on this in months. Please comment if you are still having this issue.
