### ISSUE TITLE
File Uploads Working, Cannot Edit

### ISSUE THREAD

**Issue by stevensjn** [josegonzalez/cakephp-upload#216]
Hi Jose,

Could you share with me an example of where images are being attached to records via association and then displayed in an edit form? I have setup an 'add' action but I am really struggling to figure out how to then edit the same record.

Does this functionality come with the plugin? Could you share an example? I would be happy to do a full write up of implementing this plugin for this purpose if you could help me move forward.

**Comment by davidyell** [comment]
Relates to #280
