### ISSUE TITLE
Saving Custom Path in DIR Field

### ISSUE THREAD

**Issue by kp2356** [josegonzalez/cakephp-upload#248]
Hi,

I am using the `'pathMethod' => 'primaryKey'.`

And the below path

```
'path' => '{ROOT}webroot{DS}files{DS}upload{DS}{model}{DS}{field}{DS}',
```

So, I am stuck at a point where in I want to save the DIR with a more elaborate information than just the primaryKey ID in DIR field
eg DIR field to be saved as "upload/organization/logo/1", currently its just saves "1"

I have gone though the documentation several times, but unable to understand about how to solve the above situation. Please help through  with this.

Why want this feature, when everything is happening auto-magically, using only dir field in the view helps a lot, to link the file.

Thanks.

**Comment by kp2356** [comment]
Thank you for the solution :)

**Comment by kp2356** [comment]
$this->Behaviors->Upload->settings['field']['path'] = $newPath;

should be ??

$this->Behaviors->Upload->settings['Post']['field']['path'] = $newPath;

**Comment by davidyell** [comment]
Perhaps it should be 
```php
// MyController.php
$this->Behaviors->Upload->settings[$this->modelClass]['field']['path'] = $path;
```
