### ISSUE TITLE
File Rename Call Back

### ISSUE THREAD

**Issue by harshamv** [josegonzalez/cakephp-upload#251]
Can you please add an example of how to rename the file. i have added the following but not sure how to write the callback function to pass it to the plugin.

public $actsAs = array(
        'Upload.Upload' => array(
            'display_photo' => array(
                'fields' => array(
                    'dir' => 'photo_dir'
                ),
								'thumbnailSizes' => array(
                    'small' => '250x250',
                ),
								'thumbnailMethod' => 'php',
								'path' => '{ROOT}webroot{DS}files{DS}{model}{DS}',
								'nameCallback' => 'fileRename',
            ),

        )
    );

**Comment by sagits** [comment]
Remember that you need to pass the file type too (newfilername.type). You can get it from $currentName.
