### ISSUE TITLE
Existing thumb images not delete after edit image file

### ISSUE THREAD

**Issue by monsurhoq** [josegonzalez/cakephp-upload#252]
I used following in my model :
    public $actsAs = array(
        'Upload.Upload' => array(
                'image' => array(
                    'thumbnailSizes' => array(
                        'thumb' => '300x300'
                    ),
            'thumbnailMethod' => 'php'
                )
            )
    );

It's working fine, when add a new record. But when edit image from edit form it's not removed previous thumb image.

**Comment by paoloiulita** [comment]
hello @josegonzalez and @davidyell.
i'm reopening this because i think it is a common needed behaviour.
using the provided code in an EDIT operation we have the following result:
- no file uploaded
- old image deleted

which is obviously not what we want

i tried doing this controller-side with this
```
if ( $this->request->data[ 'OperatorGroup' ][ 'picture' ][ 'size' ] != 0 ) {
	$this->request->data[ 'OperatorGroup' ][ 'picture' ][ 'remove' ] = 1;
}
```
which is horrible and not working.
the only other solution i am considering is to put and hidden field named old_picture and in the above condition use plain PHP to delete the fie from disk.
but, as stated earlier, maybe it would be nice to have this directly in the behaviour:

```
'Upload.Upload' => array(
	'picture' => array(
		'thumbnailMethod' => 'php',
		'deleteOnUpdate' => true,
		'thumbnailSizes' => array(
			'small' => '29x29',
			'profile' => '160x160'
		)
	)
)
```

what do you think about?

**Comment by paoloiulita** [comment]
BTW, i came around an ugly solution with

```
if ( $this->request->data[ 'Operator' ][ 'picture' ][ 'size' ] == 0 ) { // no picture change
	unset( $this->request->data[ 'Operator' ][ 'old_picture' ] );
	unset( $this->request->data[ 'Operator' ][ 'picture' ] );
} else {
	$file = WWW_ROOT . 'files/operator/picture/' . $id . DS . $this->request->data[ 'Operator' ][ 'old_picture' ];
	if ( file_exists( $file ) ) {
		unlink( $file );
		$file = WWW_ROOT . 'files/operator/picture/' . $id . DS . 'small_' . $this->request->data[ 'Operator' ][ 'old_picture' ];
		unlink( $file );
		$file = WWW_ROOT . 'files/operator/picture/' . $id . DS . 'profile_' . $this->request->data[ 'Operator' ][ 'old_picture' ];
		unlink( $file );
	}
}
```

this exposes a bunch of design pitfalls and summon many monsters, that's why i'm wondering a "behaviour native" solution

**Comment by davidyell** [comment]
Deleting a file is accomplished using a checkbox, so there is nothing stopping you including both the checkbox and your file upload field in your form. The management of how you want to handle that can be extended in your own code using the model callbacks.

**Comment by paoloiulita** [comment]
Sorry, i think we are talking about different subjects :)
i surely don't want a checkbox in my form (also i can't see why should i ask the user to physically delete a file he is going to overwrite in the database, IMHO it should be automatic most of the time).

If i have $this->request->data[ 'OperatorGroup' ][ 'picture' ][ 'remove' ] = 1; the old image is deleted and the component do not upload anything.

This make me assume that the functionality "automatic deletion of old assets" does not exists.
You state the oppposite, please can you point me in the right direction? Maybe i am doing something wrong?

I can for sure handle this in my model callbacks but as said earlier my opinion is that this is a very very common use case and maybe deserves it's own place, asking for opinions in that subject

thank you

**Comment by davidyell** [comment]
Great, please build that functionality and submit a PR for it.

**Comment by paoloiulita** [comment]
ok, it may take a while, i am not experienced, but i'll do my best
