### ISSUE TITLE
rename() no such file or directory. UploadBehavior.php, line 350

### ISSUE THREAD

**Issue by phpMagpie** [josegonzalez/cakephp-upload#255]
I am using this plugin with Croogo.  My file is being moved to the correct directory and saved into the dbase, but I am getting the following:

    Warning (2): rename(/tmp/phpk67bjR,/home/user/domains/domain.co.uk/public_html/webroot/files/message/cv_file/3/filename.pdf): No such file or directory [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 350]

Here's my configuration for the Contacts.Messages model:

    public $actsAs = array(
    	'Croogo.BulkProcess' => array(
    		'actionsMap' => array(
    			'read' => 'bulkRead',
    			'unread' => 'bulkUnread',
    		),
    	),
    	'Croogo.Trackable',
    	'Search.Searchable',
    	'Upload.Upload' => array(
        'cv_file' => array(
           'fields' => array(
             'dir' => 'cv_file_dir',
             'type' => 'cv_file_type',
             'size' => 'cv_file_size',
           ),
           'thumbnails' => false,
           'extensions' => array(
               'pdf',
           )
         )
      )
    );

And here's my form:

    echo $this->Form->create('Message', array(
    	'url' => array(
    		'plugin' => 'contacts',
    		'controller' => 'contacts',
    		'action' => 'view',
    		'careers',
    	),
    	'novalidate' => 'novalidate',
    	'inputDefaults' => array(
        'div' => array('class' => 'form-group'),
        'class' => 'form-control',
      ),
      'id' => 'careersForm',
      'class' => 'form-ajax',
      'autocomplete' => 'off',
      'type' => 'file'
    ));
    echo $this->Html->tag('h3', 'Upload CV', array('class'=>'text-edosz'));
    echo $this->Form->input('Message.title', array(
      'type' => 'hidden',
      'value' => 'FH System Notice: Careers CV Sent'
    ));
    echo $this->Form->input('Message.body', array(
      'type' => 'hidden',
      'value' => 'n/a'
    ));
    echo $this->Form->input('Message.name', array(
      'label' => array('text' => __d('croogo', 'Name:'), 'class' => 'sr-only'),
      'placeholder' => array('text' => __d('croogo', 'Name ...')),
      'required' => 'required',
    ));
    echo $this->Form->input('Message.email', array(
      'label' => array('text' => __d('croogo', 'Email:'), 'class' => 'sr-only'),
      'placeholder' => array('text' => __d('croogo', 'Email address ...')),
      'required' => 'required',
    ));	
    echo $this->Form->input('Message.cv_file', array(
      'type' => 'file',
      'label' => array('text' => __d('croogo', 'CV:'), 'class' => 'sr-only'),
      'placeholder' => array('text' => __d('croogo', 'Choose file')),
    ));	
    echo $this->Form->end(array(
      'label'=>__d('croogo', 'Send CV'), 
      'class'=>'btn btn-primary',
      'div' => array('class'=>'form-group')
    ));

**Comment by phpMagpie** [comment]
It's been a while, but eventually revisiting this and didn't know the full implications of getting around Croogo's manual firing of afterSave, so changed the save call in the UpoadBehaviour from:

	protected function _updateRecord(Model $model, $data) {
		if (!empty($data[$model->alias])) {
			$model->updateAll($data[$model->alias], array(
				$model->alias . '.' . $model->primaryKey => $model->id
			));
		}
	}

To

	protected function _updateRecord(Model $model, $data) {
		if (!empty($data[$model->alias])) {
			$model->save($data[$model->alias], array('callbacks'=>false));
		}
	}

This solves the issue, @josegonzalez will this cause any problems in the plugin?

**Comment by josegonzalez** [comment]
Almost certainly? I didn't know you could call a save from a save on the same model.

**Comment by phpMagpie** [comment]
It would get messy without adding `callbacks => false` to the save call, but as it is, it works.

@rchavik do developers using Croogo need to be aware that updateAll has been modified and therefore updateAll calls may behave differently in Croogo compared to how they do in an unmodified Croogo?  May need to take this conversation into Croogo's issues

**Comment by josegonzalez** [comment]
If we can disable callbacks, sure. Thats the only reason I used updateAll.

**Comment by josegonzalez** [comment]
Closing as 3.x handles this.

**Comment by phpMagpie** [comment]
Great to hear this is resolved in 3.x, doesn't help those using Croogo production sites though as we're stuck with CakePHP 2.x :(

**Comment by josegonzalez** [comment]
I'll take a PR for 2.x if you want to submit one :)

**Comment by phpMagpie** [comment]
:)
