### ISSUE TITLE
isFileUpload(...) validation failing.

### ISSUE THREAD

**Issue by antoniovassell** [josegonzalez/cakephp-upload#257]
Having an issue with isFileUpload(...)

https://github.com/josegonzalez/cakephp-upload/blob/master/Model/Behavior/UploadBehavior.php#L529

That specific line is comparing the value for the error code in the `$check` array with `UPLOAD_ERR_INI_SIZE`. 

However, if error code is '4' (character), it doesn't equal to the value `UPLOAD_ERR_NO_FILE` as that is 4 (int) because the condition is using `!==` operator. Suggest to change it to `!=`

How I attached the validation:

```
'attachment' => array(
			array(
				'rule' => 'isFileUpload',
				'message' => 'Please select a file',
			),
...
```

Anyone else having this issue?
CakePHP Upload v 1.1.1,
CakePHP 2.5.x
PHP 5.5
Windows 8.1

**Comment by davidyell** [comment]
I would be in favour of casting here and keeping the explicit comparison.
