### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by rfos** [josegonzalez/cakephp-upload#260]
Hello!

Thank you for sharing your amazing plugin.

I'm trying validate only the extension for a single upload, but the validation require a file and I can't save my data without upload a pdf file. 

Model.php

<?php
App::uses('AppModel', 'Model');

class Obra extends AppModel {

public $validate = array(
    'Arquivo_Rider' => array(
        'rule' => array('isValidMimeType', array('application/pdf')),
            'message' => 'File is not a pdf.'
        ),
 ); 
?>

Is there any way to validate only if the field has a file selected?

Thank you!

**Comment by weltonsanches** [comment]
Is the method "isValidMimeType" available to 3.x Version? When I use, I have the message "Method isValidMimeType does not exist".

**Comment by josegonzalez** [comment]
It is not. The validation rules the 3.x version provides are [here](https://cakephp-upload.readthedocs.io/en/latest/validation.html). The mimetype check went upstream into the cakephp core and is available under [mimetype](https://api.cakephp.org/3.5/class-Cake.Validation.Validation.html#_mimeType)
