### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'field list'

### ISSUE THREAD

**Issue by sagarguhe** [josegonzalez/cakephp-upload#264]
I got this error while trying to upload multiple images in a associated model here is the code I am using :

Controller:
if ($this->request->is('post') && !empty($this->request->data)):
            
            try {
                $this->CandidatesProblemReport->createWithAttachments($this->request->data);
                $this->Session->setFlash(__('Your report has been submitted '
                        . 'successfully. Thank you!'));
            } catch (Exception $e) {
                $this->Session->setFlash($e->getMessage());
            }
endif;

Model: 
 public $actsAs = array(
        'Upload.Upload' => array(
            'report_upload' => array(
                'path' => '{ROOT}{DS}webroot{DS}files{DS}{model}{DS}{field}{DS}', 
                'fields' => array(
                    'dir' => 'upload_dir' // specifying the field name for storing the image path)
  )));

public $hasMany = array(
        'Uploads' => array(
            'className' => 'CandidatesProblemReportsUpload',
            'foreignKey' => 'candidates_problem_report_id',
            'conditions' => array('Uploads.model' => 'CandidatesProblemReport')
));

View: 
echo $this->Form->input('Uploads.0.report_upload', array(
    'type' => 'file'
));
echo $this->Form->input('Uploads.0.model', array(
    'type' => 'hidden',
    'value' => 'CandidatesProblemReport'
));

What should be the problem am I doing anything wrong..

**Comment by gerrymcdonnell** [comment]
did you solve this? ive the same problem.

**Comment by josegonzalez** [comment]
I haven't solved this, and I think the reason why it failed is the `multiple => true` in the form.  Now that the 3.x version is out and works with multiple file uploads, I don't see a need to fix it for older versions (though PRs to the 2.x branch will still be welcome.).
