### ISSUE TITLE
Assign multiple images to one record id

### ISSUE THREAD

**Issue by hgnelson83** [josegonzalez/cakephp-upload#266]
Hello. This plugin is working perfectly. What I need is to upload multiple records with one input file, and assign it to one record id in the model. I've been reading the docs at: http://cakephp-upload.readthedocs.org/en/latest/polymorphic.html but I cant get it to work. The instructions are not very clear to me.

I am using this as a gallery for a javascript slider. So, what I am doing is creating multiple rows, about 15 of them for 15 images for a model. Instead I want one row, and attach it to a foreign key to another model (belongsTo Relationship.
![screen](https://cloud.githubusercontent.com/assets/207353/5203677/1298afe4-755b-11e4-9db3-0af53e4a98df.gif)

**Comment by davidyell** [comment]
Which part of the documentation do you not understand.

Creating a hasMany/belongsTo relationship is basic CakePHP. You can read more about it in the book.
http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement in a year.
