### ISSUE TITLE
Polymorphic Add/Delete Files 

### ISSUE THREAD

**Issue by manfe** [josegonzalez/cakephp-upload#267]
Imagine: Professor has_many attachments (and others models has_many attachments too)

I am able to upload files when I am creating a professor, but after that I want to delete or add more files associate with this professor. How can I do it? I tried to create a form just with the file input but all professor's attributes was created as empty as a new record instead of associate the new files to the existing record.

@josegonzalez could you help me? I can create the docs after I get it.

Thanks.

**Comment by davidyell** [comment]
Did you give the file deletion technique from the docs a go?
http://cakephp-upload.readthedocs.org/en/latest/examples.html#remove-a-current-file-without-deleting-the-entire-record

**Comment by josegonzalez** [comment]
Closing as there hasn't been any movement in a year.
