### ISSUE TITLE
Upload multiple files 

### ISSUE THREAD

**Issue by mauriciord** [josegonzalez/cakephp-upload#268]
Hi, good night !

I've used the example in my view:
-----------------
echo $this->Form->input('Image.0.attachment', array('type' => 'file', 'label' => 'Image'));
echo $this->Form->input('Image.0.model', array('type' => 'hidden', 'value' => 'Post'));
-----------------

How can i use multiple files changing this ?
Best regards,
Mauricio

**Comment by davidyell** [comment]
Just use a loop and change `0` into a value consistent with your loop as you would for any multiple form in CakePHP.
