### ISSUE TITLE
How to build the link for polymorphic files?

### ISSUE THREAD

**Issue by manfe** [josegonzalez/cakephp-upload#269]
Since the files are saved in different folder, how can I build the link based on the information saved on database?

The documentation doesn't have anything about it.

Could anyone give an example?

**Comment by davidyell** [comment]
```php
echo $this->Html->image('../files/Model/field/' . $data['Image']['image_dir'] . '/' . $data['Image']['image']);
```

Where `$data` is the data from your database for that image. This is why you store the `dir` in your database. In the example above I have used `image` as my upload field and `image_dir` as my dir field.
