### ISSUE TITLE
FileImportBehavior: How to use ?

### ISSUE THREAD

**Issue by salines** [josegonzalez/cakephp-upload#272]
Hi people,

How to use cakephp upload plugin, and import behavior  to handle the existing images and save their name into database?

I have a task to migrate data and images from joomla cms into custom CMS built into CakePHP.

In joomla cms many articles contain embedded images, into future images reside in a separate models (example: post hasmany images).

The task is to find the img tag into each post, and extract the path to the image, then take a picture with that path as the source, then create several images in different dimensions and save the image name into database.

The only what I do not know if we can use for this purpose ImportBehavior, and how?

thank you

**Comment by salines** [comment]
Or upload from url?

**Comment by josegonzalez** [comment]
Closing as we no longer support this behavior and the documentation should have been adequate.
