### ISSUE TITLE
Change path on the fly?

### ISSUE THREAD

**Issue by salines** [josegonzalez/cakephp-upload#275]
Hi people,

I use Polymorphic model for upload from several related models.

How to configure the following settings:

``` 'path' => '{ROOT}webroot{DS}img{DS}{HERE NAME OF RELATED MODEL}{DS}', ```

???

**Comment by davidyell** [comment]
I wrote a solution to this already and have added it to the documentation.
https://github.com/josegonzalez/cakephp-upload/issues/248

**Comment by salines** [comment]
Thanks, I already use the option to dynamically change the path.
