### ISSUE TITLE
rename the uploaded file before saving the data, plus you can change the file format of all that goes into a format as "jpg"

### ISSUE THREAD

**Issue by EOM** [josegonzalez/cakephp-upload#276]
Hello one question that method, I have to setiar a default name to the file upload before recording in the field.
example:
Add the name and type "img1_bla_bla_.png" to save the file with the name "return date ('YmdHisu')" and convert "jpg" quality 60.
Besides creating the "thumbnail" to "nombreForDate" ._ sizes.jpg
Etc ..

**Comment by davidyell** [comment]
All this is covered in the documentation. You can edit the quality in behaviour settings and you can use the `nameCallback` method to rename your files.

**Comment by EOM** [comment]
Yes is  OK 
function example:

// renameFile
public function renameFile($field, $currentName, $data, $options=array()){
        $ext = end(explode('.',basename($currentName)));
        $nombre = date('YmdHisu').'.'.mb_strtolower($ext);
        return $nombre;
    }

no suppot change or conver type file example "png or bmp" to "jpg" 
only permitted in the "thumbnail ;-(

**Comment by davidyell** [comment]
No, there is no support for file type conversion that I'm aware of. You'd have to extend the plugin and implement a library to change the format of the image.

**Comment by 4waymedia** [comment]
Over the past couple years, I have seen many requests for extended features outside the scope of this plugin... Perhaps added documentation is required to allow others to better understand the scope of the plugin.

Many of the additional requests would make excellent cakePhp plugins.

Regards, 
Paul

**Comment by davidyell** [comment]
Closed in favour of #280
