### ISSUE TITLE
Fixing bug when delete records with multiple files in the same Model

### ISSUE THREAD

**Issue by silviolleite** [josegonzalez/cakephp-upload#277]
I'm sorry if i did some wrong thing because im new in GitHub.
Well today i had a problem in a project using this Plugin. My project has one Model with two files "file" and "icon", so when i tried delete this records it showed an error, becouse it was trying to delete two folders "8" in the same folder "file" when it should delete one folder "8" in "file" and another in "icon".
Ok i fixed this error in the following functions "deleteFolder" and "afterDelete".
Here is the fork https://github.com/silviolleite/cakephp-upload

**Comment by josegonzalez** [comment]
Thanks for this. If you'd like to see this in master, please create a PR to the 2.x branch.
