### ISSUE TITLE
Polymorphic attachment - "Call to a member function createWithAttachments() on a non-object

### ISSUE THREAD

**Issue by kriekey** [josegonzalez/cakephp-upload#278]
Followed guide for polymorphic attachments, the following error:
Error: Call to a member function createWithAttachments() on a non-object

Post seems to be passing valid data into the model function?  Thoughts?

**Comment by kriekey** [comment]
Controller:

	public function add() {
                if ($this->request->is('post')) {
                    try {
                        $this->Post->createWithAttachments($this->request->data);
                        $this->Session->setFlash(__('The message has been saved'));
                    } catch (Exception $e) {
                        $this->Session->setFlash($e->getMessage());
                    }
                }
		$orderStatuses = $this->Order->OrderStatus->find('list');
		$orderTypes = $this->Order->OrderType->find('list');
		$users = $this->Order->User->find('list');
		$providers = $this->Order->Provider->find('list');
		$examTypes = $this->Order->ExamType->find('list');
		$this->set(compact('orderStatuses', 'orderTypes', 'users', 'providers', 'examTypes'));
	}

**Comment by kriekey** [comment]
Form Helper:

<?php echo $this->Form->create('Order',array(
    'type' => 'file',
    'inputDefaults'=>array(
        'div'=>'form-group',
        'wrapInput'=>false,
        'class'=>'form-control'
    ),
    'class'=>'well'
)); ?>
	<fieldset>
		<legend><?php echo __('Add Order'); ?></legend>
	<?php
		echo $this->Form->input('order_status_id');
		echo $this->Form->input('order_type_id');
		echo $this->Form->input('user_id');
		echo $this->Form->input('provider_id');
		echo $this->Form->input('first_name');
		echo $this->Form->input('last_name');
		echo $this->Form->input('middle_name');
		echo $this->Form->input('date_of_birth', array(
                'format' => array('before', 'label', 'between', 'input', 'error', 'after'),
                'fieldset' => false,
                'label' => 'Date of Birth (YYYY/MM/DD)',
                'before' => '',
                'after' => '',
                'class' => 'form-control date datepicker',
                'type' => 'text',
                'div' => 'form-group',
                    'error' => array(
                        'attributes' => array(
                                'wrap' => 'div', 'class' => 'alert alert-danger'
                        )
                    )
                )
                );
		echo $this->Form->input('person_nbr');
                echo $this->Form->input('primary_phone');
		echo $this->Form->input('secondary_phone');
		echo $this->Form->input('appt_details');
		echo $this->Form->input('ordering_name');
		echo $this->Form->input('ordering_contact');
		echo $this->Form->input('followup_date', array(
                'format' => array('before', 'label', 'between', 'input', 'error', 'after'),
                'fieldset' => false,
                'label' => 'Order Date',
                'before' => '',
                'after' => '',
                'class' => 'form-control date datepicker',
                'type' => 'text',
                'div' => 'form-group',
                    'error' => array(
                        'attributes' => array(
                                'wrap' => 'div', 'class' => 'alert alert-danger'
                        )
                    )
                )
                );
		echo $this->Form->input('followup_notes', array(
                    'label'=>'Order Notes'
                ));
		//echo $this->Form->input('externalID');
		//echo $this->Form->input('ng_order_num');
		//echo $this->Form->input('interfaced');
		//echo $this->Form->input('checked_out');
		//echo $this->Form->input('checked_out_by');
		echo $this->Form->input('ExamType');
                echo $this->Form->input('Image.0.attachment', array('type' => 'file', 'label' => 'Image'));
                echo $this->Form->input('Image.0.model', array('type' => 'hidden', 'value' => 'Order'));
	?>
	</fieldset>
<?php 
echo $this->Form->submit(('Submit'),array(
    'class'=>'btn btn-default'
));
echo $this->Form->end();

?>

**Comment by josegonzalez** [comment]
That assumes you have a method in your model called `createWithAttachments`. You can do whatever logic you want in that method, it doesn't come from this plugin.

**Comment by kriekey** [comment]
I have that in there, too.  Still popping the error:


    public function createWithAttachments($data) {
        // Sanitize your images before adding them
        $images = array();
        if (!empty($data['Image'][0])) {
            foreach ($data['Image'] as $i => $image) {
                if (is_array($data['Image'][$i])) {
                    // Force setting the `model` field to this model
                    $image['model'] = 'Order';

                    // Unset the foreign_key if the user tries to specify it
                    if (isset($image['foreign_key'])) {
                        unset($image['foreign_key']);
                    }

                    $images[] = $image;
                }
            }
        }
        $data['Image'] = $images;

        // Try to save the data using Model::saveAll()
        $this->create();
        if ($this->saveAll($data)) {
            return true;
        }

        // Throw an exception for the controller
        throw new Exception(__("This order could not be saved. Please try again"));
    }
