### ISSUE TITLE
Problem not enter on beforeSave

### ISSUE THREAD

**Issue by julio6114** [josegonzalez/cakephp-upload#279]
Hi all!

I encounter a problem!

When I save my model, beforeSave of UploadBehavior is not call.

I don't see where is my problem!
Thanks

**Comment by davidyell** [comment]
I would hazard a guess that the behaviour is not attached to your model. Try reading the basic example and checking it against your code.

http://cakephp-upload.readthedocs.org/en/latest/examples.html#basic-example

**Comment by julio6114** [comment]
I find!!

I've got an other behavior before Upload.Upload.
I do behavior Upload at first of array 'actAs' and it's works

Thank you!
