### ISSUE TITLE
application/pdf MimeType problem for validate

### ISSUE THREAD

**Issue by Dexter971** [josegonzalez/cakephp-upload#286]
Hi,
i have a problem with isValidMimeType validate rule.
it does not recognize 'application/pdf' mimeType.

i'm solve this problem by added '"application/pdf"' in rule (add Double quotes)

**Comment by josegonzalez** [comment]
Your mimetype is coming in with extra quotes?

**Comment by Dexter971** [comment]
Yes,
i do attachments exemple and i noted is coming with extra quotes in type field of attachments table. (only for pdf)

**Comment by josegonzalez** [comment]
This sounds like a bug in your PHP version, as the tests worked fine for me.

Since we no longer handle validation in the 3.x version, I'm closing this.
