### ISSUE TITLE
Difference in File Upload Example & File Grabbing via Form Example in Docs ?

### ISSUE THREAD

**Issue by kp2356** [josegonzalez/cakephp-upload#287]
What is the difference in File Upload Example & File Grabbing via Form Example in Docs

[File Upload Example](http://cakephp-upload.readthedocs.org/en/latest/examples.html#file-upload-example)

    <?php echo $this->Form->create('User', array('type' => 'file')); ?>
        <?php echo $this->Form->input('User.username'); ?>
        <?php echo $this->Form->input('User.photo', array('type' => 'file')); ?>
        <?php echo $this->Form->input('User.photo_dir', array('type' => 'hidden')); ?>
    <?php echo $this->Form->end(); ?>

[File Grabbing via Form Example](http://cakephp-upload.readthedocs.org/en/latest/examples.html#file-grabbing-via-form-example)

    <?php echo $this->Form->create('User', array('type' => 'file')); ?>
        <?php echo $this->Form->input('User.username'); ?>
        <?php echo $this->Form->input('User.photo', array('type' => 'file')); ?>
        <?php echo $this->Form->input('User.photo_dir', array('type' => 'hidden')); ?>
    <?php echo $this->Form->end(); ?>

If both are same then why use two headings, it is confusing. And it takes a while to realize that both are exactly the same example. (Waste of time)

**Comment by davidyell** [comment]
True, and the back end processing is really where the changes are.

**Comment by josegonzalez** [comment]
The duplicate examples were removed in the 3.x release.
