### ISSUE TITLE
File upload via URL size info

### ISSUE THREAD

**Issue by kp2356** [josegonzalez/cakephp-upload#288]
File upload via URL doesnt save the size info in db

1> size info nt getting saved in db

![image](https://cloud.githubusercontent.com/assets/1989395/6182633/ff55c970-b36d-11e4-8492-df83358e5999.png)

**Comment by kp2356** [comment]
Found solution to the First issue. :)

Add the below code after [Line 1766] (https://github.com/josegonzalez/cakephp-upload/blob/master/Model/Behavior/UploadBehavior.php#L1766)

    // Update file size info if $headers['content-length'] is not set
    if($model->data[$model->alias][$field]['size'] == 0 && $file > 0) {
        $model->data[$model->alias][$field]['size'] = $file;
    }

If you find it appropriate please add it to the main repo or should I add it ?

Issue 2 is still happening. :(

**Comment by davidyell** [comment]
Isn't reading headers generally quite unreliable? Shouldn't the size by present in the `$_FILES` array?

**Comment by kp2356** [comment]
$_FILES array will not get populated as it is from url upload feature.

**Comment by davidyell** [comment]
Ah yes, apologies, I missed that. Should it be [`filesize()`](http://php.net/manual/en/function.filesize.php) then?

**Comment by kp2356** [comment]
Not required as the [ file_put_contents() ] (http://php.net/manual/en/function.file-put-contents.php) function on [Line 1762] (https://github.com/josegonzalez/cakephp-upload/blob/master/Model/Behavior/UploadBehavior.php#L1762) returns the file size

    This function returns the number of bytes that were written to the file, or FALSE on failure.

**Comment by josegonzalez** [comment]
I'm happy to take a PR for this to the 2.x branch, but since there hasn't been movement in a while and that is no longer the stable version of CakePHP or this plugin, I am going to close this.
