### ISSUE TITLE
isWritable & isValidDir do not create the upload directory

### ISSUE THREAD

**Issue by ravage84** [josegonzalez/cakephp-upload#289]
I first started using the Upload plugin without using any validation rules on the related fields.
I got used to the fact that the plugin creates the necessary upload folder(s) by itself, which is nice.

But once I added the ``isWritable`` and ``isValidDir`` validation rules, my forms didn't work anymore on a fresh installation.

I've found out that the (base) upload path wouldn't get created as before.
Let's say I have set it up this way:
``'path' => '{ROOT}{DS}webroot{DS}files{DS}{model}{DS}{field}{DS}'``, which would translate into ``path/to/app/webroot/files/product/image1/``.

So there is a twofold problem:
a) The ``isWritable`` and ``isValidDir``validations also happen when there is no upload, which I think is a bit verbose and unnecessary
b) The behavior of the plugin changes unexpectedly once you use these data validation rules.

Possible solutions:
a) Either it only checks if there is an upload or the given behavior should be documented.
b) Either it tries to create the base upload path (if not existing) or the given behavior should be documented.

**Comment by davidyell** [comment]
Not sure if you have a typo but `'path' => '{ROOT}{DS}webroot{DS}files{DS}{model}{DS}{field}{DS}'` would end up as `app/webroot/files/product/image1/`.

Could this be down to your file permissions on your `webroot/files` folder?

**Comment by ravage84** [comment]
@davidyell yep, was a typo. But no not a permission problem. Tested on WIndows and Ubuntu.

**Comment by josegonzalez** [comment]
I'm happy to take a PR for this to the 2.x branch, but since there hasn't been movement in a while and that is no longer the stable version of CakePHP or this plugin, I am going to close this.
