### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by davidyell** [josegonzalez/cakephp-upload#292]
So it seems that `master` is now 41 commits ahead. I reckon that is worth doing a release.

https://github.com/josegonzalez/cakephp-upload/compare/1.1.1...master

I make it `1.2.2`. What your thoughts are @josegonzalez ?

* Thumbnail shell new feature (1.2.0)
* PHPCS errors fix (1.2.1)
* Convert spaces to tabs fix (1.2.2)

I haven't counted any of the documentation updates.

**Comment by josegonzalez** [comment]
1.2.0 the whole thing. Don't retroactively make releases.

**Comment by davidyell** [comment]
Are you happy for me to do the release or do you want to?

**Comment by josegonzalez** [comment]
Go on and do it.

**Comment by davidyell** [comment]
https://github.com/josegonzalez/cakephp-upload/releases/tag/1.2.0
