### ISSUE TITLE
Viewing Images once uploaded

### ISSUE THREAD

**Issue by nschembri** [josegonzalez/cakephp-upload#293]
I have installed this plugin and is working fine...

Now I need to upload multiple images, i will follow the documentation instructions... however I do not know how I can display these images once uploaded :)

**Comment by davidyell** [comment]
http://cakephp-upload.readthedocs.org/en/latest/examples.html#displaying-links-to-files-in-your-view

**Comment by q0re** [comment]
You can also use:

```
echo $this->Html->image($exampleData['Example']['dir'] . '/thumb_' . $exampleData['Example']['image'], array(
    "alt" => "Alt text"
));
```

to display images directly.

More:
http://book.cakephp.org/2.0/en/core-libraries/helpers/html.html#HtmlHelper::image
