### ISSUE TITLE
File upload does not work with basic example in the latest cakephp 2.x

### ISSUE THREAD

**Issue by Avemaar** [josegonzalez/cakephp-upload#296]
Hello,

i have to pen this case because i spent one day to make it work the plugin.
But it has not happened.The file is not uploaded to the directory with the same
parameters,only the file name.

http://cakephp-upload.readthedocs.org/en/latest/examples.html#basic-example

I found other counterpart who has the same problem:
http://stackoverflow.com/questions/12044660/cakephp-upload-plugin-not-uploading-as-attachment

Is there anything necessarily to add to the controll/add?

Would you so kind and correct the mistakes

**Comment by davidyell** [comment]
This sounds like you've not attached the behaviour to the model class.

**Comment by Avemaar** [comment]
thank you your quick answer.
I did it:
   public $actsAs = array(
        'Upload.Upload' => array(
        'image'
        )
    );

**Comment by Avemaar** [comment]
Are state that the plugin will works with the base add function in the controller?

    if ($this->request->is('post')) {
			$this->Photo->create();
			
                       $file=$this->data['Photo']['image'];//extra lines 
                       $file['name']=Sanitize::paranoid($file['name']);//extra lines without these lines there is no filename appear in the database
                        
                        if ($this->Photo->save($this->request->data)) {
				$this->Session->setFlash(__('The thumb has been saved.'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The thumb could not be saved. Please, try again.'));
			}
		}

**Comment by davidyell** [comment]
```php
<?php 
// Database
`image` VARCHAR(255) NULL;

// app/Config/bootstrap.php
CakePlugin::load('Upload.Upload');

// app/Model/Photo.php
public $actsAs = array(
	'Upload.Upload' => array(
		'image'
	)
);

// app/Controller/PhotosController.php
public function add() {
	if ($this->request->is('post') {
		$this->Photo->create();
		if ($this->Photo->save($this->request->data)) {
			$this->Session->setFlash(__('The thumb has been saved.'));
			return $this->redirect(array('action' => 'index'));
		} else {
			$this->Session->setFlash(__('The thumb could not be saved. Please, try again.'));
		}
	}
}

// app/View/Photos/add.ctp
echo $this->Form->create('Photo', array('type' => 'file'));
echo $this->Form->input('image', array('type' => 'file'));
echo $this->Form->end('Submit');
```

**Comment by Avemaar** [comment]
However i made the same as you wrote i get : 
The thumb has been saved. File name is wrote into
the database but no physical file was uploaded

**Comment by wewo** [comment]
I have the same problem. File is simply no uploaded, and when I debug post request data I get this:

```
array(
	'User' => array(
		'username' => 'testuser',
		'photo_dir' => '',
		'photo' => array(
			'name' => 'pic123.jpg',
			'type' => 'image/jpeg',
			'tmp_name' => 'C:\wamp\tmp\php8DE8.tmp',
			'error' => (int) 0,
			'size' => (int) 42524
		)
	)
)
```

Is this OK? I mean photo_dir is empty and I don't understand why temp file is saved to WAMP temp (btw the file is not there). In the documentation I see no config for temp folder. Thank you for help.

**Comment by Avemaar** [comment]
i am a bit calm down now.I thought i was to dump to implement it.
My xampp servers settings are correct,i was able to implement an
own fileupload function,and there correctly works.

**Comment by wewo** [comment]
So you are not using this plugin? Anyway, can someone help?

**Comment by Avemaar** [comment]
i need to use it because i have to re-use in more models

**Comment by davidyell** [comment]
@Avemaar Your form isn't working because you've removed the `'type' => 'file'`. I would imagine that your file isn't being uploaded due to a file permissions problem with your file system.

@wewo Your file upload is correct. An uploaded file in PHP will always provide a file upload array as you have shown. As you are on Windows, you might well have an issue with writing files to the filesystem.

As I don't develop on Windows I cannot help with this issue.

**Comment by Avemaar** [comment]
I've just removed to try the other type,but also work.
I created a core fileupload and it was working properly,
so i think there is no problem with permission

**Comment by Avemaar** [comment]
A working example with almost basic instructions.It is well upload the files:



public function add() {
 if ($this->request->is('post')) {
      if(!empty($this->data['Totalcar']['photos']['name'])){
      $file=$this->data['Totalcar']['photos'];
      $file['name']=Sanitize::paranoid($file['name']);
      debug(WWW_ROOT.'\img' .DS. time().$file['name']);
       
      $this->request->data['Totalcar']['photos'] = time().$file['name'];
      
      if($this->Totalcar->save($this->request->data)) {
       move_uploaded_file($file['tmp_name'], APP .WEBROOT_DIR.'\img' .DS. time().$file['name']);  
       $this->Session->setFlash(__('Your Report has been saved.'));
              return $this->redirect(array('action' => 'index'));
          }
     }
                  $this->Session->setFlash(__('Unable to add your Report.'));
           
 }
	}

**Comment by davidyell** [comment]
Glad you found a solution.

**Comment by Avemaar** [comment]
Excuse me but this uploaded code is nothing to do with the plugin.
I've just wanted to show that the permissions is setup correctly in xampp

**Comment by davidyell** [comment]
It seems the issue is with the documentation, as the plugin code works fine.

**Comment by Avemaar** [comment]
How do you mean with Documentation?

**Comment by davidyell** [comment]
I think that the basic example could be expanded to be more in depth.

The reason that there is no details on controller methods is because the plugin is a behaviour which attaches to your models and uses model callbacks to upload files during the save process. There is no need to do any processing of the upload in your controllers, as it's all taken care of at the model level because it's data.

**Comment by Avemaar** [comment]
I debugged this:

![debug_output](https://cloud.githubusercontent.com/assets/8372600/7332395/9a932f16-eb3d-11e4-98ea-893f625879a7.png)
![output2](https://cloud.githubusercontent.com/assets/8372600/7332396/9f6258aa-eb3d-11e4-8bc4-266c0cf53e22.png)

However i attached the Upload.Upload in the model by the plugins i can not see the Upload plugin included

**Comment by Avemaar** [comment]
How to debug it why the move_uploaded_file does not copy the file to the folder?

**Comment by macayer** [comment]
Bump. I have that same problem with the latest version for cake 2.X. and latest Cake 2.X

public $actsAs = array(
        'Upload.Upload' => array(
            'attachment' => array(
                'thumbnailSizes' => array(
                    'thumb' => '80x80'
                )
            )
        )
    );

this will save record in table Attachment with correct attachment name, but it doesn't upload the file physically. Permissions are correct on webroot/files. Any Idea?

**Comment by josegonzalez** [comment]
@Avemaar `path` does not go under the `fields` key, but is at the same level.
