### ISSUE TITLE
DB Not being populated

### ISSUE THREAD

**Issue by marksie1988** [josegonzalez/cakephp-upload#298]
I have followed the article in your documentation for many to one images. 

For some reason my database creates a new line but has none of the following fields populated: 

model  / name / attachment / dir / type / size 

what could be causing this im struggling to find the issue?

**Comment by davidyell** [comment]
Sounds like the data you're saving is empty.

**Comment by marksie1988** [comment]
Below is the array that is used for "Saveall" to the database: 

    Array(
        [Event] => Array(
                [EventName] => dasdasdadasd
                [Description] => asdas
                [EventDate] => Array(
                        [month] => 05
                        [day] => 06
                        [year] => 2015
                        [hour] => 07
                        [min] => 01
                        [meridian] => pm
                    )
                [Enabled] => 1
            )
        [Image] => Array(
                [0] => Array(
                        [model] => Post
                        [attachment] => Array(
                                [name] => Capture.PNG
                                [type] => image/png
                                [tmp_name] => /tmp/phpVPorNS
                                [error] => 0
                                [size] => 57523
                            )
                    )
            )
    )

**Comment by davidyell** [comment]
That's odd, in Cake PHP 2, an event isn't passed. Are you trying to use this with Cake PHP 3?

**Comment by marksie1988** [comment]
I am using CakePHP 2.5.6

**Comment by marksie1988** [comment]
Ok I figured it out, it was because i changed the $hasMany to $hasOne
