### ISSUE TITLE
HABTM Not saving data

### ISSUE THREAD

**Issue by marksie1988** [josegonzalez/cakephp-upload#299]
Hi,

Im not sure if this is the best place to ask or stackoverflow but here goes. I am using the CakePHP-Upload plugin, I had it working using your many to one tutorial. I now have a requirement to change this to be many to many but i cant get the function to save all the data for the attachment. I have removed the foreign_key field and now use a new table linking to my "Events" table

Events: 

    id, name, date, enabled
	1, Event1, today, 0
	2, Event2, tomorrow, 0
	
Attachments:

    id, model, name, attachment, dir,type,size,active
	1, Event, , Capture.PNG, 1, image/png, 57523, 1
	
Events_Attachments:

	id, Events_id, Attachments_id
	1, 1, 1
	1, 2, 1    

In my event model I have the function: 

    public function createWithAttachments($data) {
        // Sanitize your images before adding them
        $images = array();
        if (!empty($data['Image'][0])) {
            foreach ($data['Image'] as $i => $image) {
                if (is_array($data['Image'][$i]) && $image['attachment']['size'] > 0) {
                    // Force setting the `model` field to this model
                    $image['model'] = 'Event';

                    $images[] = $image;
                }
            }
        }
        $data['Image'] = $images;

        // Try to save the data using Model::saveAll()
        $this->create();
        if ($this->saveAll($data)) {
            CakeLog::write('debug', 'ModelArray'.print_r($data, true));
            return true;
        }

        // Throw an exception for the controller
        throw new Exception(__("This post could not be saved. Please try again"));
    }
    public $hasAndBelongsToMany = array(
        'Image' =>
            array(
                'className' => 'Attachment',
                'joinTable' => 'events_attachments',
                'foreignKey' => 'events_id',
                'associationForeignKey' => 'attachments_id',
                'unique' => true,
                'limit' => '1',
            )
    );

In the Attachment model i have: 

    public $actsAs = array(
        'Upload.Upload' => array(
            'attachment' => array(
                'thumbnailSizes' => array(
                    'xvga' => '1024x768',
                    'vga' => '640x480',
                    'thumb' => '80x80',
                ),
                'path' => '{ROOT}webroot{DS}img{DS}{field}{DS}'
            ),
        ),
    );
    public $hasAndBelongsToMany = array (
        'Event' => array (
            'className'             => 'Event',
            'joinTable'             => 'events_attachments',
            'foreignKey'            => 'attachments_id',
            'associationForeignKey' => 'events_id',
            'unique'                => true,
            'limit'                 => '1',
        )
    );

the array data that is sent is: 

	[Event] => Array
        (
            [EventName] => xcvxcvxcv
            [EventDate] => Array
                (
                    [month] => 05
                    [day] => 15
                    [year] => 2015
                    [hour] => 02
                    [min] => 24
                    [meridian] => pm
                )

            [Description] => asdscvxcv
            [Enabled] => 0
        )
    [Image] => Array
        (
            [0] => Array
                (
                    [model] => Event
                    [attachment] => Array
                        (
                            [name] => dc954172be8eb19416b921efb1f61da6.jpg
                            [type] => image/jpeg
                            [tmp_name] => /tmp/phpwPDVTm
                            [error] => 0
                            [size] => 17378
                        )
                )
        )

Any assistance would be appreciated.

**Comment by josegonzalez** [comment]
Sorry we weren't able to help you way back when. Since this is no longer the supported version of the plugin, I'm going to close this now. Feel free to comment if you are still having this issue.
