### ISSUE TITLE
AJAX/cakephp-upload

### ISSUE THREAD

**Issue by hkharod** [josegonzalez/cakephp-upload#300]
Would this work if the file is being sent with AJAX?

**Comment by josegonzalez** [comment]
Yes, you just have to send the data in the correct format for CakePHP's save method.

**Comment by hkharod** [comment]
Thanks, could you give me a tip on how the file/image data should be formatted for the save method? Right now I'm sending the image data as json then decoding it in my cake controller. After that, I've been stuck on how to format the decoded image data before initiating the save. I would be extremely grateful for any tips, not getting much help from stack right now. Thanks Jose!
