### ISSUE TITLE
isValidExtension validation on form data without uploaded file

### ISSUE THREAD

**Issue by bakroistvan** [josegonzalez/cakephp-upload#302]
Hi

Is it possible to do isValidExtension validation on form data without uploaded file.
I mean if one submits a form without a file that user got a validation error.
But my plan was to ignore this validation error.

Thanks
Steve

**Comment by josegonzalez** [comment]
[See the docs](https://cakephp-upload.readthedocs.org/en/latest/validation.html#isvalidextension), there is an example.
