### ISSUE TITLE
old file remove from editor when upload new

### ISSUE THREAD

**Issue by urfusion** [josegonzalez/cakephp-upload#303]
I am uploading files one by one . So after uploading one file when I go for second one it remove the first one. Is there any configuration by which first file remain there too. here is the one blog which explaining this but I am not able to find that JS. Or is there any way to show the preview just after uploading the file

http://plugins.krajee.com/file-input-ajax-demo/1

and Second  issue or problem is, is there any way by which I can remove the file if I didn't submit the form.

**Comment by josegonzalez** [comment]
Both those things sound like they are outside of the scope of this plugin, so I'm going to close this for now.
