### ISSUE TITLE
unable to use namecallback

### ISSUE THREAD

**Issue by jaimevada** [josegonzalez/cakephp-upload#308]
Kindly provide guidance or example for how to use namecallback in this plugin.
Thanks in advance

**Comment by davidyell** [comment]
``php
// app/Model/Example.php
public function rename($field, $currentName, array $data, array $options) {
    return $currentName . date('Y-m-d');
}
```

**Comment by harshamv** [comment]
this is what @davidyell code give `IMG_1683.jpg2015-08-10` 

which is wrong.

**Comment by davidyell** [comment]
Examples rarely write your code for you.

**Comment by jaimevada** [comment]
Thanks davidyell, one more question how can i create folder by foreign key instead of primary key.

**Comment by davidyell** [comment]
Look in `$data`

**Comment by jaimevada** [comment]
i try in namecallback
$filename=$userid.'{DS}'.$currenttime."_".$currentName;
But it change name like "22{DS}20150815_xyz.pdf"
instead of 
22 -> "20150815_xyz.pdf"

**Comment by harshamv** [comment]
```
public function rename($field, $currentName, array $data, array $options) {
		$ext = pathinfo($currentName, PATHINFO_EXTENSION);
		$name = uniqid().'.'.mb_strtolower($ext);
		return $name;
	}
```

try this

**Comment by jaimevada** [comment]
its not working. 
i want to create foreign key wise folder.

**Comment by harshamv** [comment]
what exactly are u trying to do?

**Comment by jaimevada** [comment]
currently my uploaded files are stored in following location: 
webroot/files/umoocdetail/filepath/22/xyz.pdf
webroot/files/{MODEL}/{field}/{primary_key}/{filename}

i want to store that files like:
webroot/files/{MODEL}/{field}/{foreign_key}/{filename}

**Comment by jorisvaesen** [comment]
Just chance the behavior path config on the fly from the controller.

**Comment by jaimevada** [comment]
I use following for change behavior path in controller:
$this->Behaviors->Upload->settings[$this->modelClass]['field']['path'] = "{ROOT}webroot{DS}files{DS}{model}{DS}{field}{DS}".$this->request->data['Umoocdetail']['user_id']."{DS}";

and $actsAs same as above comment but its not working. is it right way to do this?

**Comment by marquesferreira** [comment]
why i dont have access to $currentName?
