### ISSUE TITLE
Image Stretch Problem

### ISSUE THREAD

**Issue by sanjay-github** [josegonzalez/cakephp-upload#309]
Hi,

I want an image to be scaled and if it is small, it should be stretched as well according to given dimension.
 
For larger images , it's working fine but for small images it's getting scaled but not stretched
and that looks kind of improper to me.

This is my current configuration -

 public $actsAs = array(
        'Upload.Upload' => array(
            'category_image' => array(
                'path' => '{ROOT}webroot{DS}img{DS}uploads{DS}category{DS}',
                'mimetypes' => array('image/bmp',
                    'image/gif',
                    'image/jpeg',
                    'image/pjpeg',
                    'image/png',
                    'image/vnd.microsoft.icon',
                    'image/x-icon',
                    'image/x-png'
                ),
                'extensions' => array('png', 'jpg', 'jpeg'),
                'thumbnailSizes' => array(
                    '281' => '[281x155]',
                    'thumb' => '[60x45]',
                    '130' => '[130x130]',
                )
            )
        )
    );

Please help me out. Thanks !

**Comment by davidyell** [comment]
Your configuration is best fit, if you want to scale images you'd want to scale them to a specific size using 

`100w`

See the docs.
https://cakephp-upload.readthedocs.org/en/latest/thumbnails.html

**Comment by sanjay-github** [comment]
But 100w will resize according to width only, what about the height. Can I use something like 100w×100h.
