### ISSUE TITLE
Micro FIX or Bug, to updateBehavior.php in line "1499" AND "1502"

### ISSUE THREAD

**Issue by EOM** [josegonzalez/cakephp-upload#310]
Hello,
I am writing to comment on a micro bug, detect and extention makes the work better.
You got to add "@" in the two overhead lines that are in the print screen, which is attached here. Thus the error messages that I can to make the code execution is prevented.

Print add Code in master Source:
http://s25.postimg.org/4jksppk6n/Print_de_pantalla_650.jpg

**Comment by EOM** [comment]
Add change

Print show in code:
http://s25.postimg.org/jgt9qpxf3/Print_de_pantalla_651.jpg

**Comment by EOM** [comment]
Add code for change IMG origen source, with the function "handleUploadedFileCallback"
Avoid error in the source orgine to create thumbnails


Print code add show:
http://s25.postimg.org/4nj7jpf1r/Print_de_pantalla_653.jpg

Lines: 1547 to 1553

// Change extencion Orgien source img..?
        if(@file_exists($filename)==true){
            $e = explode(".", $filename);
            $ext = array_pop($e);
            // Update now extencion, for change
            $pathInfo['extension'] = $ext;
        }

**Comment by davidyell** [comment]
Using the @ operator to suppress warnings is discouraged.

**Comment by josegonzalez** [comment]
Sorry we weren't able to help you way back when. Since this is no longer the supported version of the plugin, I'm going to close this now. Feel free to comment if you are still having this issue.
