### ISSUE TITLE
Image Cropping with desired coordinates, ex: crop 400x300, at x:30, y:40

### ISSUE THREAD

**Issue by artfanvikram** [josegonzalez/cakephp-upload#312]
Thanks for the awesome plugin, i need to use the cropping feature little more advanced, that is to add specific cropping location with (x,y) coordinates. Just like its possible on facebook. In this case i will be passing coordinates at runtime obtained via jQuery imagearea select plugin.
Can you please help me on how can i achieve this with existing plugin.

Thank you
Vikram

**Comment by josegonzalez** [comment]
This isn't possible with the currently plugin and is not a feature I intend to add, sorry.
