### ISSUE TITLE
Save according group id?

### ISSUE THREAD

**Issue by whte** [josegonzalez/cakephp-upload#313]
Hi,

I have a question.

So the upload working perfectly, but how do I assign according to group id instead of the id itself?

Each group is having multiple photos, how can I set the path to put the files according to group id? instead of one folder for each photo.

**Comment by davidyell** [comment]
Wouldn't you associate this in the model? So that `Something hasMany Attachment`

**Comment by jorisvaesen** [comment]
I guess you could change the behavior path configuration on the fly from your controller.
