### ISSUE TITLE
[feature] Inside white band, use blurry image of original

### ISSUE THREAD

**Issue by salines** [josegonzalez/cakephp-upload#315]
This is the basic idea, where we have so-called portrait photos, but we need to view them as landscape thumbnails . It would be nice to have the option instead of the white band to create a blurred background of our original photo, as in this example.

![Blurry](http://s10.postimg.org/4js45rqnt/batch.jpg)

**Comment by davidyell** [comment]
I find this far more visually distracting personall.y

**Comment by josegonzalez** [comment]
This is out of the scope of the current plugin version. Sorry.

**Comment by salines** [comment]
@davidyell 
I would not say that it is confusing, the same technique is widely used in the show amateur video clips on TV, because the vast majority of smartphone users use the camera incorrectly.

@josegonzalez ¸

UploadBehavior.php aftter line 1452 I add:

imagefill($img, 0, 0, imagecolorallocate($img, 255, 255, 255));
imagecopyresampled($img, $src, 0, 0, 0, 0, $destW, $destH, $srcW, $srcH);
$amout_of_blur = 100;
for ($i=0; $i < $amout_of_blur ; $i++) { 
    imagefilter($img, IMG_FILTER_GAUSSIAN_BLUR);
}
imagecopyresampled($img, $src, ($destW - $resizeW) / 2, ($destH - $resizeH) / 2, 0, 0, $resizeW, $resizeH, $srcW, $srcH);

This is only a test.

Thanks.

**Comment by josegonzalez** [comment]
Cool, glad you found a way to do this.
