### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by vaughany** [josegonzalez/cakephp-upload#316]
Hi all. I'm trying and failing to install this plugin into CakePHP 3.  I'm using the 3.x-dev branch, and installing with Composer:

```
$ composer require josegonzalez/cakephp-upload "3.x-dev"
```

I add the following to bootstrap.php:

```
Plugin::load('Upload');
```

...but when I refresh the web page, I get a 'missing plugin' exception. Apparently it's being looked for in plugins/ (which it should be, according to the [documentation](http://cakephp-upload.readthedocs.org/en/latest/index.html), but I think it's still based on 2.x) whereas it's most definitely installed in vendor/josegonzalez/cakephp-upload/

I'm quite new to CakePHP 3 and I think I'm doing everything I should be, but obviously not or it would be working...  Can anyone point out where I'm going wrong?

**Comment by davidyell** [comment]
This plugin isn't fully compatible with 3.x yet, and is still under active development.

**Comment by josegonzalez** [comment]
You would need to do something like `Plugin::load('Josegonzalez/Upload)`.

**Comment by vaughany** [comment]
Thanks @josegonzalez, I knew it would be something reasonably obvious.  I'd help with the docs if I could but I don't know enough to be helpful.

**Comment by josegonzalez** [comment]
Closing as the documentation for 3.x is complete and this was released.
