### ISSUE TITLE
Uploading dataUri image, with cakephp-upload plugin

### ISSUE THREAD

**Issue by artfanvikram** [josegonzalez/cakephp-upload#318]
HI,
Thanks for the awesome plugin,
I happen to face an issue uploading dataUri image, can you please guide me on this,
Where i am currently,
1. Get dataUri with crop feature on canvas,
2. Store this uri on input field
3. Next at the backend I have variable that has dataUri, then I am not getting how to send it to plugin for upload, so that automatic cropping happens and its recorded onto database.

Please you help is much needed.

Thank you

**Comment by josegonzalez** [comment]
This sort of feature is outside the scope of this plugin. Sorry.

**Comment by jorisvaesen** [comment]
You could write the data uri to a file, manipulate the request data array and pass it to the plugin.
