### ISSUE TITLE
Issue while uploading PNG file.

### ISSUE THREAD

**Issue by sanjay-github** [josegonzalez/cakephp-upload#319]
Hi,

The plugin gives sometime error while uploading PNG file and if it gets uploaded it does not create thumbnails of given dimensions and instead it creates all thumbnails of same dimensions.

This is my configuration and I am using inbuilt PHP GD library, CakePHP 2.6.2 version. -

```
public $actsAs = array(
        'Upload.Upload' => array(
            'image' => array(
                'path' => '{ROOT}webroot{DS}img{DS}uploads{DS}users{DS}',
                'mimetypes' => array('image/bmp',
                    'image/gif',
                    'image/jpeg',
                    'image/pjpeg',
                    'image/png',
                    'image/vnd.microsoft.icon',
                    'image/x-icon',
                    'image/x-png'
                ),
                'extensions' => array('png','jpg', 'jpeg'),
                'thumbnailSizes' => array(
                    'xvga' => '1024x768',
                    'vga' => '210x158',
                    'thumb' => '60x45',
                    'header_pic' => '38x38',
                    '130' => '130x130',
                    'sneakpeek' => '247x303',
                    'review' => '69x65',
                    'profile' => '260x157',
//                    'sneakpeek' => '303h',
                )
            )
        )
        , 'UtilsAdmin', "Containable",
    );
```

Hoping to get your help ASAP. Its kind of urgent.
Thanks !

**Comment by josegonzalez** [comment]
What is the "some error" you get?

**Comment by sanjay-github** [comment]
Warning (2): imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error:  [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1499]

Warning (2): imagecreatefromjpeg() [function.imagecreatefromjpeg]: '/opt/lampp/htdocs/demo/mozaty/app/webroot/img/uploads/company/41/xvga_1441394577_logo.jpg' is not a valid JPEG file [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1499]

Warning (2): exif_read_data(xvga_1441394577_logo.jpg) [function.exif-read-data]: File not supported [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1502]

Warning (2): imagecreatefromjpeg() [function.imagecreatefromjpeg]: gd-jpeg: JPEG library reports unrecoverable error:  [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1499]

Warning (2): imagecreatefromjpeg() [function.imagecreatefromjpeg]: '/opt/lampp/htdocs/demo/mozaty/app/webroot/img/uploads/company/41/vga_1441394577_logo.jpg' is not a valid JPEG file [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1499]

Warning (2): exif_read_data(vga_1441394577_logo.jpg) [function.exif-read-data]: File not supported [APP/Plugin/Upload/Model/Behavior/UploadBehavior.php, line 1502]

**Comment by josegonzalez** [comment]
Sounds like your png file is being modified as a jpeg, so perhaps it's not a valid png file.

**Comment by jorisvaesen** [comment]
Maybe the plugin could check mimetype in stead of extension to prevent these type of errors?

**Comment by sanjay-github** [comment]
Exactly , it should validate the mimetypes and if its not proper there should be some mechanism to tell user to upload valid image.

**Comment by josegonzalez** [comment]
You can use the validation rules to [check mimetypes](https://cakephp-upload.readthedocs.org/en/latest/validation.html#isvalidmimetype). Up to the developer to set that up.

Since we've figured out the issue, I'm closing it.
