### ISSUE TITLE
3.x - Drop $table arg of WriterInterface::_constructor()

### ISSUE THREAD

**Issue by ADmad** [josegonzalez/cakephp-upload#320]
The $table arg seems redundant. The `DefaultWriter` doesn't require a table instance and if required table alias can fetched from entity instance.

**Comment by ADmad** [comment]
Similarly `$table` arg can be dropped from `TransformerInterface::__construct()` and `ProcessorInterface::__construct()` too.

**Comment by josegonzalez** [comment]
I actually do not want to do this. The reason for this is that it may actually be useful to have a direct reference to the table (in case someone bastardizes the entity coming in). Feel free to not use the table reference if you don't want to.
