### ISSUE TITLE
3.x - Add `InflectedTransformer` 

### ISSUE THREAD

**Issue by ADmad** [josegonzalez/cakephp-upload#321]
It's common practice to sanitize the file name (especially when saving to local filesystem), so having a `InflectedTransformer` or `SlugTransformer` which sluggifies the file name would be nice.

**Comment by ADmad** [comment]
I see that you can use a callback to modify the file name returned by `File\Path\Filename\DefaultTrait::filename()` but that is used only for setting filename to entity property after the file has already been saved. This doesn't seem overly useful too me.

**Comment by ADmad** [comment]
@josegonzalez Thoughts on this? I can make a PR if you agree.

**Comment by josegonzalez** [comment]
Sure. I'd prefer if the docs were finished out first for 3.x so I can merge it to master though...

**Comment by ADmad** [comment]
Docs is something I can't help you with :stuck_out_tongue: 

What do you prefer `InflectedTransformer` or `SlugTransformer`?

**Comment by ADmad** [comment]
Done in #323
