### ISSUE TITLE
3.x - Running tests leaves file behind.

### ISSUE THREAD

**Issue by ADmad** [josegonzalez/cakephp-upload#325]
After running `DefaultWriteTest.php` you end up with a `file.txt` in the plugin's root. So either `vsfStream` isn't doing it's job or i am misunderstanding it's purpose.

**Comment by josegonzalez** [comment]
Maybe we're using it wrong, but probably a `vfsStream` issue.

**Comment by ADmad** [comment]
I think it's a usage issue. The tests use `vfsStream` to read file but not to write files. They pass just regular [string](https://github.com/josegonzalez/cakephp-upload/blob/3.x/tests/TestCase/File/Writer/DefaultWriterTest.php#L44) for file to write to and the flysystem adapter by default writes to the [plugin's ROOT](https://github.com/josegonzalez/cakephp-upload/blob/3.x/src/File/Writer/DefaultWriter.php#L141).

I tried changes 'file.txt' to `vfsStream::url('root/foo.txt')` but adapter doesn't understand the url and create nested directory structure `vfs: / root / foo.txt`.

**Comment by ADmad** [comment]
So the tests also need to use a virtual filesystem adapter like https://github.com/thephpleague/flysystem-vfs
