### ISSUE TITLE
3.x - Uploadbehavior::beforeSave() incorrectly checks return value of WriterInterface::write()

### ISSUE THREAD

**Issue by ADmad** [josegonzalez/cakephp-upload#329]
WriterInterface::write() returns an array and in case of failure the return value would be like `[false]`. The behavior incorrectly checks that return value as `if (!$success)` instead of checking the non of the array values are false.

**Comment by ADmad** [comment]
[This](https://github.com/josegonzalez/cakephp-upload/blob/3.x/tests/TestCase/Model/Behavior/UploadBehaviorTest.php#L174) return value is incorrect since `write()` returns an array not boolean.

**Comment by josegonzalez** [comment]
Fix it?
