### ISSUE TITLE
Thumbnail generate shell error

### ISSUE THREAD

**Issue by sanjitbauli** [josegonzalez/cakephp-upload#331]
It seems there are some issues with the shell to genrate thumbnails/ 
It says 
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ModelName.dir' in 'field list'

**Comment by sanjitbauli** [comment]
Finally i found out the solution. In fact there isn't anywhere mentioned that. 
In model i have to set 
'fields' => array(
                    'dir' => 'fieldname'
                )
Great job !!

**Comment by davidyell** [comment]
This configuration option is mentioned [in the basic example.](http://cakephp-upload.readthedocs.org/en/latest/examples.html#basic-example)
