### ISSUE TITLE
Down-scaling rather than cropping 

### ISSUE THREAD

**Issue by mateuszgwozdz** [josegonzalez/cakephp-upload#333]
Hello Mr.Gonzalez,
thank you for your work, it's great contribution to Cakphp community!

My question - I would like to down-scale, as well as crop pictures [now only cropping is possible]. I need to preserve original aspect ratio, my website uses responsive images, but sometimes uploaded image is to big to be rendered responsively. At the moment I have a thumbnail size of as an example 1000x1000,
if the upload is 2000x1000 it will be cropped to 1000x1000 cutting half of the picture, I would like it to be downscaled to 1000x500 instead. Other images like profile picture still need to be cropped. How can we accomplish this?

I was thinking to add another option in settings:
thumbnailSizes: [...],
scaledSizes: [1000x1000],

Thank you!
Best regards

**Comment by josegonzalez** [comment]
Not possible in the 2.x version. I drop image manipulation completely in the 3.x branch, in favor of users implementing that with their preferred library - like Imagine or Intervention Image.

You could try some of the file callbacks in 2.x to manipulate the image manually?

**Comment by mateuszgwozdz** [comment]
Ok, will do that, thank you for the instant answer! :+1:
