### ISSUE TITLE
When uploading PNG, or GIF file, the cropped thumbnail has the transparent filled with black.

### ISSUE THREAD

**Issue by artfanvikram** [josegonzalez/cakephp-upload#334]
Hi, please help me on this, I ve been facing thumbnail generation issues when i upload PNG or GIF. After the thumbnail generation the images cropped are in jpegs, but the transparent background should have been filled with white instead of black. So please can you suggest me what can i do to fix this issue.
Thank you
Vikram

**Comment by josegonzalez** [comment]
You are probably using invalid thumbnail parameters to generate them. Unfortunately, this feature was removed in a recent release, so you'll need to patch your version to handle this.
