### ISSUE TITLE
Read permissions?

### ISSUE THREAD

**Issue by JLCraddock** [josegonzalez/cakephp-upload#344]
I would like to be able to display the image that was uploaded, but every upload has the initial permissions of 700, so I have to go in and manually update the permissions to 644, is there a setting to do this in the plugin? I did not find anything obvious in the documentation. Is it something I have to do on my server? Changing the folders permissions did not seem to change anything.

**Comment by josegonzalez** [comment]
What version of the plugin are you using?

**Comment by JLCraddock** [comment]
Version 3.0

**Comment by josegonzalez** [comment]
Can you try changing [this line](https://github.com/josegonzalez/cakephp-upload/blob/master/src/File/Writer/DefaultWriter.php#L149) to say `AdapterInterface::VISIBILITY_PUBLIC`?

**Comment by JLCraddock** [comment]
That did not appear to change anything. Still showing 700 for uploaded images.

**Comment by josegonzalez** [comment]
For new images, or the existing ones? If you're on irc.freenode.net/#cakephp, I can discuss this directly (I'm `savant` there).

**Comment by josegonzalez** [comment]
Fixed by https://github.com/josegonzalez/cakephp-upload/commit/5fc83b862dbdf3057a6bad80b6dd9561e3c839b7. Release 3.0.4 has this fix in place.
