### ISSUE TITLE
Rename the file 

### ISSUE THREAD

**Issue by Schabaani** [josegonzalez/cakephp-upload#345]
I am struggling to use this plugin for uploading videos.

It works so fine without 'nameCallback' . However, When using it for renaming my file, it does not work. I mean it changes the name and trying to move the file with new name. Finally there is no uploaded file. but it saves the new name & directory for that file.
I've tested everything , I guess there is a problem in "UploadBehavior.php::beforSave". 

 In the file I commented 2 things that can show my problem better.

Thanks in advance :]

[MoviesTable.txt](https://github.com/josegonzalez/cakephp-upload/files/73127/MoviesTable.txt)

**Comment by josegonzalez** [comment]
This should be fixed now.
