### ISSUE TITLE
write only basename on image_dir field

### ISSUE THREAD

**Issue by dario86** [josegonzalez/cakephp-upload#346]
On Cakephp 3.x project I have this configuration, because i want to save in `image_dir` field, only the "microtime" string:

```
$this->addBehavior('Josegonzalez/Upload.Upload', [
    'image' => [
        'rootDir' => WWW_ROOT . 'upload{DS}companies{DS}gallery{DS}',
        'path' => '{microtime}{DS}',
        'fields' => [
            'dir' => 'image_dir',
        ],
    ],
]);
```
Unfortunately `rootDir` does not work. How can I save on `image_dir` only path basename?

**Comment by josegonzalez** [comment]
What do you mean, `rootDir` does not work?

**Comment by dario86** [comment]
Yeah, image is saved in `ROOT . '{microtime}{DS}' `

**Comment by josegonzalez** [comment]
Ooops! That should be `filesystem.root`. `rootDir` was from 2.x. I've updated the docs.

**Comment by dario86** [comment]
Good! it works (But in this case, cannot use Tokens)

**Comment by josegonzalez** [comment]
You shouldn't need tokens. In your case, you aren't replacing it with any magic it seems, so you can just set it to:

```php
ROOT . DS . 'upload' . DS . 'companies' . DS . 'gallery' . DS
```

Would tokens be useful?
