### ISSUE TITLE
 Error: Class 'Entity' not found " in the view "index.ctp"

### ISSUE THREAD

**Issue by lpalacin** [josegonzalez/cakephp-upload#347]
Hello. 

Congratulations for this plugin: is very necessary and usefull, but I have a problem in the view:  Error: Class 'Entity' not found " in the view "index.ctp".  Thank you very much. Without to sove it, I can go on with my little project
 
Model: 
[TdrsTable.txt](https://github.com/josegonzalez/cakephp-upload/files/75504/TdrsTable.txt)

View: 
[index.txt](https://github.com/josegonzalez/cakephp-upload/files/75505/index.txt)

I don't undesrtand this sentence, what is it her funcion.

<?= $entity = new Entity(['fitxer' => 'pdfFile.pdf', 'fitxer_dir' => '7']); 

Thank you very much

**Comment by josegonzalez** [comment]
Can you gist your `index.ctp` file?

**Comment by davidyell** [comment]
This doesn't sound related to the plugin at all to me. The actual error is because you're trying to use the `Cake\ORM\Entity` class, and are missing a use statement. However, the cause of this error is two-fold.

Firstly, you should be setting the entity instance to a view variable in your controller, and the second issue is that you shouldn't be using the entity class directly in your view templates.

**Comment by josegonzalez** [comment]
Yeah, your `$tdr` object probably already has the requisite fields. I've updated the documentation to make it more clear where the `$entity` variable is coming from, but basically I think you misinterpreted that example.

**Comment by lpalacin** [comment]
Thanks. I put on the entity instance in my controller, and says:

Error: Class 'App\Controller\Entity' not found File C:\xampp\htdocs\tdr\src\Controller\TdrsController.php Line: 14

The controller is this:

[TdrsController.txt](https://github.com/josegonzalez/cakephp-upload/files/75602/TdrsController.txt)

**Comment by lpalacin** [comment]
Hi ! I solve the problem with this code in my view:

 <?=  $this->Html->link('Veure', '/' . $tdr->fitxer_dir . '' . $tdr->fitxer); ?>

And it tries to go tot URL: 
http://localhost/tdr/webroot/files/Tdrs/fitxer/name.pdf

But now the sentence doesn't go to open the file because causes this error:
Error: Create the class WebrootController below in file: src\Controller\WebrootController.php
It looks for a controller that doesn't exists: webroot

Ho can I do for open the files?
Thank you

**Comment by lpalacin** [comment]
It works !!

 I don't use finally an $entity variable. I use the $tdr variable, which contains the record data.

This is the code:

[TdrsTable.txt](https://github.com/josegonzalez/cakephp-upload/files/76316/TdrsTable.txt)

[TdrsController.txt](https://github.com/josegonzalez/cakephp-upload/files/76317/TdrsController.txt)

[index.txt](https://github.com/josegonzalez/cakephp-upload/files/76318/index.txt)


Thank you
