### ISSUE TITLE
Was not able to setup without settings

### ISSUE THREAD

**Issue by djonatanb** [josegonzalez/cakephp-upload#356]
I get a type error from configuring it like this:
```
$this->addBehavior('Josegonzalez/Upload.Upload', [
            'photo',
        ]);
```
had to add some content to the setting array like:
```
$this->addBehavior('Josegonzalez/Upload.Upload', [
            'file' => [
                'path' => 'webroot{DS}{field}{DS}{model}',
            ],
        ]);
```

**Comment by josegonzalez** [comment]
Can you gist the entire error?

**Comment by jubbs** [comment]
I had the same issue. Here is my error
![screenshot from 2016-02-04 17 03 47](https://cloud.githubusercontent.com/assets/7624010/12805562/4b6e29ea-cb61-11e5-9864-f56ca059dc17.png)

**Comment by josegonzalez** [comment]
@jubbs can you gist the following:

- Your form view
- Your *entire* controller
- The *entire* model

**Comment by jubbs** [comment]
The error does not return once the plugin has been run once succesfully so it only happens on a fresh install

https://gist.github.com/jubbs/b100c931dcf73b9d9897

**Comment by josegonzalez** [comment]
Run once successfully?

**Comment by jubbs** [comment]
If you put some settings in the behaviour as suggested by djonatanb then it works. If you then remove them it still works.

**Comment by josegonzalez** [comment]
For existing records? Does it work for new records still after removing the config?

**Comment by josegonzalez** [comment]
*bump*
