### ISSUE TITLE
Update readthedocs.org for 2.x

### ISSUE THREAD

**Issue by davidyell** [josegonzalez/cakephp-upload#367]
With the deployment of the new 3.x version of the plugin I cannot find a way to browse the 2.x version documentation.

I've tried the version popup in the bottom corner, but it doesn't seem to list any 2.x versions.

This essentially means that any legacy projects still using the 2.x version now have no documentation to refer to for the 2.x configuration settings, which is what I was looking for.

Unfortunately I don't know, or use readthedocs, so I can't offer a solution.

Ref: https://docs.readthedocs.org/en/latest/versions.html#how-we-envision-versions-working

**Comment by josegonzalez** [comment]
I link to the 2.x docs in the readme.

**Comment by jorisvaesen** [comment]
This seems not to be the case since the link in the 2.x readme redirects to http://cakephp-upload.readthedocs.org/en/latest/ (which is the 3.x branch)

**Comment by josegonzalez** [comment]
You can read the docs by going to the docs directory.

If someone wants to figure this out for me, that would be great, otherwise I'm not going to spend time fixing documentation for an older version of this plugin.

**Comment by davidyell** [comment]
Yeah, I had a read of the readthedocs docs, but couldn't really figure it out. I was hoping it would be something simple, but if it's pulling from the repo then it probably means maintaining two versions of the documentation in the current master branch, which will get confusing real quick.

I had hoped that someone familiar with readthedocs.org would be able to assist with a quick fix. If I have some time, I'll have a play about and see what I can turn up.

If it does transpire that it would mean having both 3.x and 2.x version documentation in the master branch, would you be cool with that @josegonzalez?

**Comment by josegonzalez** [comment]
No, I don't want to include 2.x docs in the 3.x docs.

**Comment by jorisvaesen** [comment]
Could this help you out: http://read-the-docs.readthedocs.org/en/latest/features.html#versions ?

**Comment by davidyell** [comment]
So it'd just be a matter of @josegonzalez logging into readthedocs.org and telling it to build docs for the `1.3.0` tag?

**Comment by josegonzalez** [comment]
Done.

**Comment by davidyell** [comment]
Awesome, thanks @josegonzalez 

Works for me :+1: 

http://cakephp-upload.readthedocs.org/en/2.x/
