### ISSUE TITLE
Support RepositoryInterface and EntityInterface

### ISSUE THREAD

**Issue by josegonzalez** [josegonzalez/cakephp-upload#369]
This should allow us to support non-sql databases.

**Comment by josegonzalez** [comment]
Closing, RepositoryInterface is for something else completely.

**Comment by josegonzalez** [comment]
Re-opening, I know what I meant now...

**Comment by josegonzalez** [comment]
Seems like this isn't really too possible due to the fact that Behaviors are scoped to Tables, not the RepositoryInterface.

**Comment by davidyell** [comment]
Table does implement the RepositoryInterface though, so if it's implementing the table it'll still implement the interface right?

**Comment by ADmad** [comment]
@davidyell Right.

@josegonzalez The write and processor interface which have typehinting for `Table` aren't tightly coupled with behavior, so you can change it to `RepositoryInterface` if you want.
