### ISSUE TITLE
Como puedo configurar las opciones para Thumbnails?

### ISSUE THREAD

**Issue by fernastereo** [josegonzalez/cakephp-upload#370]
Instalamos correctamente el plugin, esta funcionando bien, pero no hemos podido configurar las opciones para crear los thumbnails de las imagenes que subimos a traves de nuestra aplicacion. Lo que queremos es mostrar una vista previa de cada imagen en un listado. 

![thumbnails](https://cloud.githubusercontent.com/assets/17733505/13620707/bade36ae-e55f-11e5-8416-096515d9293a.png)

He visto un ejemplo en el que se configura en el behavior las siguientes opciones:

```php
        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'photo' => [
                'fields' => [
                    'dir' => 'photo_dir',
                    'size' => 'photo_size', 
                    'type' => 'photo_type', 
                ],
                'thumbnailMethod' => 'php',
                'thumbnailSizes' => array(
                        'vga' => '640x480',
                        'thumb' => '150x150'
                ),
                'deleteOnUpdate' => true,
                'deleteFolderOnDelete' => true
            ],
        ]);
```

Con esto, funciona el cargue de la imagen pero no crea los thumbnails, por favor ayudanos!!!!!!

Gracias.

**Comment by josegonzalez** [comment]
Este blog post te puede ayudar con el version para cake3: http://josediazgonzalez.com/2015/12/05/uploading-files-and-images/

**Comment by fernastereo** [comment]
Seguí los pasos tal como lo indica y obtengo el siguiente error: 
{primaryKey} substitution not allowed for new entities

Aqui esta mi codigo, por favor ayudameeeeee

![01](https://cloud.githubusercontent.com/assets/17733505/13654300/6ba146a0-e625-11e5-8b0f-3d2b6f0878d7.png)
![02](https://cloud.githubusercontent.com/assets/17733505/13654301/6bab1e8c-e625-11e5-8c53-a7b218aa240a.png)
![03](https://cloud.githubusercontent.com/assets/17733505/13654302/6badfecc-e625-11e5-84ea-229aa0cdbaf5.png)

Gracias por adelantado
