### ISSUE TITLE
Using the file_dir but with another column then primary id

### ISSUE THREAD

**Issue by tgoeminne** [josegonzalez/cakephp-upload#380]
Hi,

I have a table which look like this:

partfiles

id
part_id
file
file_dir

I am trying to save files and I have set the 'dir' => 'file_dir', now when I add a new file it will store the file into a directory that matches the id of the file added. What if I wanted to save the file in another directory based on a the value of item_id. This way it is eassier that many files which belong to the same item are stored into the same directory.

I have tried setting the file_dir value in the add form, but it seems to not use the value that I set, rather it just saves based on the primary id.

Any idea?

**Comment by josegonzalez** [comment]
Can you paste the code you tried?

**Comment by tgoeminne** [comment]
This is in the model:

public $actsAs = array(
'Upload.Upload' => array(
'file' => array(
'fields' => array(
'dir' => 'file_dir',
'type' => 'filetype',
'size' => 'filesize',
),
),
),
);


In the view:

<?php
echo $this->Form->input('part_id', array('type' => 'hidden', 'value' =>
$part['Part']['id']));
echo $this->Form->input('user_id',array('type' => 'hidden', 'value' =>
$_SESSION['Auth']['User']['id']));
echo $this->Form->input('file', array('type' => 'file'));
echo $this->Form->input('file_dir', array('type' => 'hidden', 'value' =>
$part['Part']['id']));
?>

The controller:

public function add($id = null) {
if ($this->request->is('post')) {
$this->PartFile->create();
if ($this->PartFile->save($this->request->data)) {
$this->Session->setFlash(__('The part file has been saved'));
return $this->redirect(array('action' => 'index'));
} else {
$this->Session->setFlash(__('The part file could not be saved. Please, try
again.'));
}
}elseif(!isset($id)){
$this->Session->setFlash(__('Files needs to belong to a part'));
return $this->redirect(array('action' => 'index'));
}
$part = $this->PartFile->Part->find('first',array('conditions' =>
array('Part.id' => $id)));
$this->set(compact('part'));
}




2016-03-31 14:52 GMT+08:00 Jose Diaz-Gonzalez <notifications@github.com>:

**Comment by jorisvaesen** [comment]
Is it an option to set `['pathMethod' => 'flat']` and use `nameCallback` to prepend the dir based on `part_id`? 
Be aware that this could lead to unexpected behavior when uploading more than one file with the same name and `part_id`.

**Comment by jorisvaesen** [comment]
@tgoeminne _bump_

**Comment by tgoeminne** [comment]
I kind of want if i set the file dir that it is used. Instead of creating
fil dirs based on the id.

**Comment by jorisvaesen** [comment]
You're losing me here. 
Can you give more detail about what functionality you would like to see in this plugin?

**Comment by josegonzalez** [comment]
You want to force override the directory field? If you want to do that, you can either change the upload path dynamically like [so](https://github.com/josegonzalez/cakephp-upload/blob/2.x/docs/examples.rst#changing-the-upload-path-dynamically) or set `handleUploadedFileCallback` as mentioned [here](https://github.com/josegonzalez/cakephp-upload/blob/2.x/docs/configuration.rst).

There are no further methods of modifying the path in a 2.x application, and there will be no further active feature development on that branch. Consider upgrading your application if possible to 2.x, where the Upload plugin is a bit more flexible in how you can specify paths.

Note: In my opinion, your users don't care about where the files are stored, so long as they can download them, so trying to make your directory structure look nice is really only for you.
