### ISSUE TITLE
couldn't find package

### ISSUE THREAD

**Issue by novis921111** [josegonzalez/cakephp-upload#382]
when i'm trying to install this plugin using composer, it said couldn't find package josegonzales/cakephp-upload at any version of my minimum stability... anyway it's stable... 

so, am i spelling the package wrong or it's because my minimum stability... if yes what should i change it to? 

or is it just me too dumb for this? :'(((

thank you anyway....
![capture](https://cloud.githubusercontent.com/assets/12060919/14200528/ac8da3f0-f815-11e5-9bd1-14bee998fff3.JPG)

**Comment by josegonzalez** [comment]
Yeah, thats not how you spell my name.

**Comment by novis921111** [comment]
OMG it is really my bad... how could i couldn't notice that -_-''

**Comment by josegonzalez** [comment]
It's even in the repo name lolol.

**Comment by novis921111** [comment]
lol i don't know... it's just.. when we watch telenovela and anything like that, we usually heard names like yours dubbed in our languange and pronounced with 's' so i think it's my habit to use s instead z... 
so yeah i read it as gonzales so i write it gonzales... in fact, it's gonzalez :'') 

i feel bad cause it's your name :'''( 
forgive the newbie..

**Comment by josegonzalez** [comment]
<3
