### ISSUE TITLE
SlugTransformer

### ISSUE THREAD

**Issue by bolshas** [josegonzalez/cakephp-upload#385]
Hi,

I don't know it his was intended, but SlugTransformer does not save a sluggified version of the filename to the database table, therefore the file is not deleted by Writer afterwards.

Andrius

**Comment by josegonzalez** [comment]
What version of the plugin/cakephp are you using, and can you gist your configuration?

**Comment by bolshas** [comment]
3.4.0

**Comment by bolshas** [comment]
3.2.9 cakephp

**Comment by bolshas** [comment]
This is basically it:
       ```
 $this->addBehavior('Josegonzalez/Upload.Upload', [
            'photo' => [
                'keepFilesOnDelete' => false,
                'transformer' => 'Josegonzalez\Upload\File\Transformer\SlugTransformer'
            ],
        ]);
```

**Comment by bolshas** [comment]
if I upload the file named "a a a.jpg", the file gets saved as "a-a-a.jpg", but the table record is "a a a.jpg"

**Comment by josegonzalez** [comment]
Transformers are for changing files. You can:

- upload a video
- create 10 thumbnails
- return the video and thumbnails

All from a single transformer. They do not affect what is saved in the database. For that, you'll need a PathProcessor.

**Comment by bolshas** [comment]
ok, thanks
