### ISSUE TITLE
Problem uploading multiple files (images)

### ISSUE THREAD

**Issue by hgnelson83** [josegonzalez/cakephp-upload#387]
I've been having problems uploading multiple images to one field in the model. In the past when I used cake 2.x with this same plugin, I had to create 14 fields to upload 14 different images related to a model, among with 14 other fields for dir, and 14 fields for caption for a slideshow that I was able to successfully create for one of my clients. What I wish, is to do this without repeating the amount of fields to upload images. I'm currently using cakephp 3.2.8. Right now I am in the development stage under a Wamp local environment. 

The problem is that only the last selected image gets uploaded, and when I try to make the form to upload multiple images I get the following error: https://nopaste.me/view/533ccf8f
I then try to make it work for the bookmark tutorial but I get the same results. The actual code: https://gist.github.com/hgnelson83/e4bb72ce0087fb049791b93439a7e801

**Comment by jorisvaesen** [comment]
You should read this article to see how many images can be related to a gallery:
http://cakephp-upload.readthedocs.io/en/2.x/polymorphic.html

Furthermore you will have to manipulate the upload array to fit the array the plugin expects.

**Comment by hgnelson83** [comment]
Thats for cake 2.x. 

I am going to try other ways to do this, outside of this plugin.

**Comment by hgnelson83** [comment]
Thats for cake 2.x. I am going to try other solutions. Thanks anyway.

**Comment by ADmad** [comment]
@hgnelson83 The concept still remains the same. You just need to adjust the code as per 3.x.
