### ISSUE TITLE
Latest Cake 2 release

### ISSUE THREAD

**Issue by davidyell** [josegonzalez/cakephp-upload#388]
The cake 2 branch is a little behind, and it would be good to push out a new release, probably `1.3.1` for cake 2.

Last release, `Sep 22, 2015` `1.3.0`
Last change, `Apr 21, 2016`

**Comment by davidyell** [comment]
@josegonzalez Are you cool if I make a new release for 2.x?

**Comment by josegonzalez** [comment]
Go for it.

**Comment by davidyell** [comment]
Resolved by `1.3.1` release.

https://github.com/josegonzalez/cakephp-upload/releases/tag/1.3.1
