### ISSUE TITLE
'keepFilesOnDelete' => false does not seem to work when setting 'path'

### ISSUE THREAD

**Issue by babslinc** [josegonzalez/cakephp-upload#395]
I can't get your plugin to delete the photo file when entry to database is deleted using the option 'keepFilesOnDelete' => false  when I configure the path at the same time. This is the code I have in the BabiesTable

```
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('babies');
        $this->displayField('title');
        $this->primaryKey('id');
        // START: IMPORTANT PART HERE
        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'picture' => [       
                'path' => 'webroot{DS}img{DS}baby',
                //'pathMethod' => 'flat', tried this from your prior setup but doesn't work
                'keepFilesOnDelete' => 'false',
            ],
        ]);
```

What configuration am I missing from here?

**Comment by josegonzalez** [comment]
False should be a boolean, not a string.

**Comment by babslinc** [comment]
Thanks for quick response. I forgot to say I tried false as a boolean and a string and neither works. Any other ideas where I might be messing up.

**Comment by josegonzalez** [comment]
https://github.com/josegonzalez/cakephp-upload/blob/aa01f018a675bbec631e2cccc8934da27743eb14/src/Model/Behavior/UploadBehavior.php#L119

That is the code that handles file deletion. Can you write a test case that proves that files aren't deleted? That would help me narrow down what's happening.

**Comment by n0f** [comment]
Does not it can be fixed by modified as follows?

```php
$this->addBehavior('Josegonzalez/Upload.Upload', [
    'picture' => [       
        'path' => 'webroot{DS}img{DS}baby{DS}',  // append {DS}
        //'pathMethod' => 'flat', tried this from your prior setup but doesn't work
        'keepFilesOnDelete' => 'false',
    ],
]);
```

The default value of `'path'` is `'webroot{DS}files{DS}{model}{DS}{field}{DS}'`.
So, there is a possibility that the `'path'` is missing.
There may be a shortage in the documentation for `'path'`.(Because my English is not good, I want to ask the modification to other people.)

**Comment by josegonzalez** [comment]
Stop using a string for the value of `keepFilesOnDelete`.

**Comment by n0f** [comment]
I'm sorry. Fixed a comment.

**Comment by babslinc** [comment]
Looking at the afterDelete function in UploadBehavior, you have the file to delete defined specifically as:
$dirField = Hash::get($settings, 'fields.dir', 'dir');
$file = [$entity->{$dirField} . $entity->{$field}]; //(line124)

whereas on the older Upload version you had the file to be deleted defined as: 
$this->deleteFolder($model, $options['path']);

which would allow me to define a different path in the table (model) and have the 
'keepFilesOnDelete' => false;
 setting(option) work without further modification of the code. I guess I should have stuck to your default directory structure, but I liked the old ability to modify the path and have plugin work on both ends (adding, deleting, and replacing).

**Comment by josegonzalez** [comment]
That should build the correct path to your images. Is only a single image being destroyed, or are no images being destroyed?

Again, if you can write a failing unit test, that would be great.

**Comment by babslinc** [comment]
The issue was that I did not include the 'dir' column in my tables since I was converting an existing site.  So the 'dir' column is required, and needs to show the full path for each entity to have the file for that entity deleted. So one more quick question, since I keep trying to get your plugin to do what it wasn't designed to do (I do appreciate your efforts on this awesome plugin). Why didn't you include the 'deleteOnUpdate' option in this current iteration? Have any idea how I could institute it on my end?

**Comment by josegonzalez** [comment]
Because, thats why.

You would need to keep track of old file uploads somehow, and then delete them in the `afterSave` if the save completed successfully.
