### ISSUE TITLE
upload multiple files is not working for me,can you please guide me

### ISSUE THREAD

**Issue by mxj333** [josegonzalez/cakephp-upload#396]
upload multiple files is not working for me,can you please guide me
$this->addBehavior('Josegonzalez/Upload.Upload', [
'photo',
'video'
]);

**Comment by josegonzalez** [comment]
What happens when you try to upload multiple files? Can you gist your entire controller, model, and template?

**Comment by mxj333** [comment]
Thanks, but I think I can handle it .
