### ISSUE TITLE
Set content type on filesystem adapter

### ISSUE THREAD

**Issue by felipe-pereira-xpantion** [josegonzalez/cakephp-upload#402]
Hi, I'm uploading files to S3, and I need to set the content type (mainly images, text files and pdfs), trying something like this;

```
$this->addBehavior('Josegonzalez/Upload.Upload', [
            'file' => [
                'path' => Configure::read('USE_S3') ? '' : 'files{DS}{model}{DS}{field}{DS}',
                'nameCallback' => function($data, $settings){
                    $ext = pathinfo($data['name'], PATHINFO_EXTENSION);
                    return Text::uuid().'.'.$ext;
                },
                'filesystem' => [
                    'adapter' => $adapterProvider::getFileSystemAdapter($data['name'])
                ]
            ],
        ]);
```
Of course that doesn't works because of data being undefined, so my question is how do I get the file info to pass it to the method that returns the adapter?.

The idea is that $adapterProvider::getFileSystemAdapter will give me the adapter with the right mime type set (not sure how to do that yet, but that may be out of the scope of your plugin).

Cake beginner here so don't be afraid to explain something even if it looks obvious, thanks.

**Comment by felipe-pereira-xpantion** [comment]
FYI I ended up using a customized writer (`WriterInterface`) and in the `writeFile `function added this

...
```
if (Configure::read('USE_S3')) {
  $fileSettings = [
	  'visibility' => 'public',
	  'ContentType' => $this->getMimeType($file),
	  'ContentEncoding' => 'gzip'
  ];
}
```
...

`if ($filesystem->writeStream($tempPath, $stream, $fileSettings)) {...`

... 
and in the table

```
'filesystem' => [
	'adapter' => $adapter
],
'writer' => 'App\Lib\DocumentsWriter'
```

**Comment by josegonzalez** [comment]
Yep that sounds like the way forward :)
