### ISSUE TITLE
How to use a global model for file-uploads?

### ISSUE THREAD

**Issue by TheMiller2015** [josegonzalez/cakephp-upload#405]
Hello!

I have a bigger project which "heavily" depends on file-uploads. So I created a db-table / model for files (id, user_id, section, file_path, file_name, file_type etc...).

The section identifies in which part of the app the file will be displayed (e.g. "profile" => user-avatar, "tutorials" => a downloadable pdf file in the tutorials-section and so on...).

Is it possible, to include the upload-behaviour to the user-model and to the tutorials-model, but to store the meta-data of the file in the "files"-table? Or is this a bad idea?

If this is possible, do I have to call some methods of the files-model/controller, or is this just a config-parameter?

I tried to figure out and read the docs - but I'm new to this plugin.

Thanks in advance!

**Comment by jorisvaesen** [comment]
Although this is from the the 2.x docs, it can be perfectly used in 3.x: http://cakephp-upload.readthedocs.io/en/2.x/polymorphic.html

**Comment by TheMiller2015** [comment]
Thank you very much. I'll have a look tomorrow (hopefully).
