### ISSUE TITLE
Update file size after transform

### ISSUE THREAD

**Issue by felipe-pereira-xpantion** [josegonzalez/cakephp-upload#407]
Hi, I'm uploading an image and use a transformer (like in the example [here](http://josediazgonzalez.com/2015/12/05/uploading-files-and-images/)).

The only difference is that I only save the thumbnail and discard the original

```
return [
    $tmp => $data['name']
 ];
```

The issue is that the size saved is the one from the original image, not from the thumbnail that will finally end on the server.

How can I set the correct `size`?, tried updating the entity but the data is already set on `beforeSave`with the original size.

Thanks

**Comment by josegonzalez** [comment]
$entity->set() maybe?

**Comment by felipe-pereira-xpantion** [comment]
Tried that but even if the correct size is set on memory (added debug line to confirm) what gets saved has the original size, looks like when I set the new size is too late since the entity is not going to be persisted again, any ideas?

**Comment by josegonzalez** [comment]
Maybe we could emit an event after [this line](https://github.com/josegonzalez/cakephp-upload/blob/master/src/Model/Behavior/UploadBehavior.php#L107) where you can modify things to your heart's content? Would you be willing to submit a PR + tests for that?

**Comment by felipe-pereira-xpantion** [comment]
I'ld love to contribute to this project, but I just started working part time with php and cake a few weeks ago, maybe I could throw some lines after googling about what you mean by `events`, but for the tests I don´t even how to run them.
If you think of a possible workaround that doesn't involve modifying your plugin just mention it and I'll investigate further, thanks.

**Comment by felipe-pereira-xpantion** [comment]
Finally I achieve this by setting the new size in the transformer;

```
// Set the new size here so it can be updated in afterSave
$entity->set('file_size', filesize($tmp));
```

And then persist the change in `afterSave`

```
public function afterSave($event, $object)
{
	// Check if file was transformed to a smaller version and update file_size
	$entity = $event->data['entity'];
	$finalSize = $entity->extractOriginal($entity->visibleProperties())['file_size'];

	if ($object['file_size'] > $finalSize) {
		$Documents = TableRegistry::get('Documents');
		$Documents->query()->update()
			->set(['file_size' => $finalSize])
			->where(['id' => $object['id']])
			->execute();
	}
}
```

Probably not the most elegant solution, so let me know if improvements can be made here, thanks.
