### ISSUE TITLE
Issue using a Table method as the nameCallback

### ISSUE THREAD

**Issue by drmonkeyninja** [josegonzalez/cakephp-upload#408]
I'm not sure if this is a bug or my implementation, but when attempting to pass `nameCallback` as an array for the current model `is_callable` in `DefaultTrait` is failing because the values of `nameCallback` have been duplicated.

I am using version 3.6.0 of the plugin.

This is how I'm initialising the behaviour with the `nameCallback` for the current class:-

```
public function initialize(array $config)
{
    parent::initialize($config);

    $this->table('images');
    $this->displayField('name');
    $this->primaryKey('id');

    $this->addBehavior('Josegonzalez/Upload.Upload', [
        'filename' => [
            'path' => 'webroot{DS}files{DS}images{DS}',
            'nameCallback' => ['\App\Model\Table\ImagesTable', 'fixUploadFilename'],
            'keepFilesOnDelete' => false
        ]
    ]);

    $this->addBehavior('Timestamp');
}
```

If I then debug the value of `$this->settings` in the trait the `nameCallback` has been duplicated:-

```
[
    'filename' => [
        'path' => 'webroot{DS}files{DS}images{DS}',
        'nameCallback' => [
            (int) 0 => '\App\Model\Table\ImagesTable',
            (int) 1 => 'fixUploadFilename',
            (int) 2 => '\App\Model\Table\ImagesTable',
            (int) 3 => 'fixUploadFilename'
        ],
        'keepFilesOnDelete' => false
    ]
]
```

Am I using the plugin incorrectly, or is there a bug here? 

I know that if I use a global method this can be easily got round, but I want to avoid using global methods here and define the callback within the scope of my table class.

**Comment by josegonzalez** [comment]
Can you gist the whole table class?

**Comment by josegonzalez** [comment]
*bump*

**Comment by drmonkeyninja** [comment]
Sorry @josegonzalez I've been away for a few days. I think we can close this issue now as I have now got things working so think it must have been something about my implementation causing the bug.

**Comment by mstroink** [comment]
I'm having the same issue. I think it has something to do with the following:
I've created a self-associated parent relationship. Something like:
 
```
<?php

class NodesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->belongsTo('ParentNodes', [
            'className' => 'MyApp/Nodes.Nodes',
            'foreignKey' => 'parent_id'
        ]);

        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'image_url' => [
                'path' => 'webroot{DS}files{DS}{model}{DS}{field}{DS}{primaryKey}',
                'nameCallback' => ['MyApp\Nodes\Model\Table\NodesTable', 'renameFile'],
                'transformer' => 'Josegonzalez\Upload\File\Transformer\SlugTransformer'
            ],
        ]);
    }
}
```

Now, when I upload a file and post the data, the Initialize function runs multiple times (?!). So also the UploadBehavior config got merged multiple times.

```
//vendor/cakephp/cakephp/src/Core/InstanceConfigTrait.php : 278
$this->_config = Hash::merge($this->_config, Hash::expand($update));
```
 And then you end up with something like this:

```
[
	'path' => 'webroot{DS}files{DS}{model}{DS}{field}{DS}{primaryKey}',
	'nameCallback' => [
		(int) 0 => 'MyApp\Nodes\Model\Table\NodesTable',
		(int) 1 => 'renameFile',
		(int) 2 => 'MyApp\Nodes\Model\Table\NodesTable',
		(int) 3 => 'renameFile'
	],
	'transformer' => 'Josegonzalez\Upload\File\Transformer\SlugTransformer'
]
```
