### ISSUE TITLE
How to get and save additional data from adapter?

### ISSUE THREAD

**Issue by diego-carrera** [josegonzalez/cakephp-upload#414]
When using an adapter, lets say Google Storage or S3, how to get and save por example, the public url in another field?

I have the documents table with the following fields.
```
id, name, document, dir, public_url
```

Using [flysystem-google-cloud-storage](https://github.com/Superbalist/flysystem-google-cloud-storage)
```php
// 
$client = new StorageClient([
      'projectId' => 'project-id',
      'keyFilePath' => 'path-to-credentials.json',
]);

$adapter = new GoogleStorageAdapter(
      $client,
      $client->bucket('my-bucket')
);

$this->addBehavior('Josegonzalez/Upload.Upload', [
  'document' => [
    'path' => 'documents{DS}',
    'filesystem' => [
      'adapter' => $adapter,
    ]
  ],
]);
```

If I wanted to get the public url for the uploaded file I'd call 
```php
// gets the url of the file in the specified bucket
$adapter->getUrl('documents/{$thefile}')
```

Is it possible whithin the uploader plugin?

**Comment by josegonzalez** [comment]
I don't think thats currently possible, would you like to open a pull request to implement such functionality?

**Comment by diego-carrera** [comment]
Yeah I might, what would be the ideal place to do that?
I'm not that familiarized with the codebase.

Thanks.

**Comment by josegonzalez** [comment]
What sort of interface are you looking for in order to complete the task? Lets start there and work backwards.

**Comment by diego-carrera** [comment]
Ok, so imagine this use case:

The user needs to complete a form where he or she needs to upload his avatar.
We are storing avatars on a google cloud bucket to save server space.

So the user submits the form, and the uploader uses the flysystem adapter to send it to the bucket, now ideally I should store the public url of the uploaded object somewhere on the DB to show the avatar on the website, and not having to use the api every time an avatar is shown on the website.
With something like this:
```HTML
<img src="$user->avatar_public_url; ?>
```

So the data should be set alongside dir, file_type, file_size fields, ready to be saved on the record.

Does this makes any sense?

**Comment by josegonzalez** [comment]
Yep, I'm just asking what you'd like the user interface to look like.

**Comment by diego-carrera** [comment]
Sorry for the wait, work is getting in the way of me doing other stuff.
I'll be closing this issue for now, until i have a little spare time.

Thnx for the support.
