### ISSUE TITLE
Renaming a file after it has been uploaded.

### ISSUE THREAD

**Issue by ZackaryMurphy** [josegonzalez/cakephp-upload#416]
I currently have a nameCallback set to rename the files on upload. However, for my current project it is desirable to allow certain users to rename files at any time after upload. I'm currently trying this:

```php
    $oldname = null;

    if (!empty($request->data['filename'])) {
        if (pathinfo($request->data['filename'], PATHINFO_EXTENSION) != $extension) {
            $request->data['filename'] .= '.' . $extension;
        }
        $oldname = $layout->file;
        $layout->file = $request->data['filename'];
        unset($request->data['filename']);
    }
    $layout = $table->patchEntity($layout, $request->data);
    if ($table->save($layout)) {
        if ($oldname) {                    
            $this->_renameLayout($oldname, $layout->file);
         }
    }
```

where rename layout uses php's rename function to handle the actually file movement. However trying it like this triggers the error in the UploadBehavior's beforeSave that sets the field back to the original value. I've also tried simply letting patchEntity handle the renaming, but with the same results. How can I allow for renaming of a file after it has been uploaded with this plugin? I can rename it myself, but this doesn't update the row in the database.

**Comment by Spriz** [comment]
Why don't you just give them an arbitrary name in the db? 🤔

**Comment by ZackaryMurphy** [comment]
I do give them an arbitrary name. I'd like to allow certain users to change that name later after it has been uploaded.

**Comment by davidyell** [comment]
This to me doesn't sound like anything to do with the upload plugin. This sounds like wanting to edit a record.

I would approach this by updating my edit template, to include a new conditional input field of `filename`, which is displayed when an upload is present in the record. Then in my controllers edit method I'd look for this field, and just use PHP's `rename()` method to change the filename, and update the entity, before saving it.

**Comment by ZackaryMurphy** [comment]
That is what I was doing. The behavior's beforeSave was catching that and resetting the entities filename in the database. I hadn't considered unloading the behavior before doing so, though. Thank you.
