### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by clementcrownrise** [josegonzalez/cakephp-upload#420]
I installed your cakephp upload plugin, but on clicking on the submit button, i get the below error.

![image](https://cloud.githubusercontent.com/assets/3583726/20848373/213b2d58-b8d2-11e6-90dd-d22ae4002c4a.png)

I actually installed with composer, but I didnt see the plugin file and folder in the cakephp Plugin directory, so I had to manually download the plugin from github and place the folder in the cakephp plugin directory, 

Please what could me the cause of this problem? and how do I fix it?

**Comment by davidyell** [comment]
If you are downloading plugins using Composer, then they'll end up in the `/vendor` folder, not in `src/Plugin`. I'd also assume that if you're using Composer, you're using Cake 3, which would be looking in `/vendor` and not in `Plugin`

**Comment by ADmad** [comment]
Use composer to install the plugin so that the plugin and it's decencies are properly installed.

**Comment by josegonzalez** [comment]
@clementcrownrise As @davidyell says, the plugins will be installed inside of `/vendor`. CakePHP knows how to load them up, so you just need to add it to your bootstrap at that point.

The `src/Plugin` folder is for plugins *you've* developed for your particular application.

**Comment by clementcrownrise** [comment]
I used composer to do the installation, the plugin files were not in vendor file also, however, I will try again.

Thanks

**Comment by josegonzalez** [comment]
They won't be top-level, but in some nested directory.

**Comment by clementcrownrise** [comment]
![image](https://cloud.githubusercontent.com/assets/3583726/20851221/65e6e3ea-b8df-11e6-864c-34f48c1a967d.png)


Telling me nothing to install,

**Comment by josegonzalez** [comment]
It's already installed then. Here is what I get in an app that has it installed already:

```
$ ll vendor/josegonzalez/cakephp-upload/
total 72
drwxr-xr-x@ 14 jose  staff   476B Nov 30 22:40 .
drwxr-xr-x@  7 jose  staff   238B Nov 30 22:40 ..
-rw-r--r--@  1 jose  staff   320B Nov 21 09:02 .editorconfig
-rw-r--r--@  1 jose  staff    22B Nov 21 09:02 .gitignore
-rw-r--r--@  1 jose  staff   353B Nov 21 09:02 .scrutinizer.yml
-rw-r--r--@  1 jose  staff   1.8K Nov 21 09:02 .travis.yml
-rw-r--r--@  1 jose  staff   2.9K Nov 21 09:02 CONTRIBUTING.md
-rw-r--r--@  1 jose  staff   1.1K Nov 21 09:02 LICENSE.txt
-rw-r--r--@  1 jose  staff   2.7K Nov 21 09:02 README.md
-rw-r--r--@  1 jose  staff   1.1K Nov 21 09:02 composer.json
drwxr-xr-x@ 12 jose  staff   408B Nov 21 09:02 docs
-rw-r--r--@  1 jose  staff   1.2K Nov 21 09:02 phpunit.xml.dist
drwxr-xr-x@  6 jose  staff   204B Nov 21 09:02 src
drwxr-xr-x@  6 jose  staff   204B Nov 21 09:02 tests
```

**Comment by clementcrownrise** [comment]
Ok, thanks for your support

![image](https://cloud.githubusercontent.com/assets/3583726/20851605/b7bc415e-b8e1-11e6-9ffc-e898140bfe80.png)
hope I can add the upload to multiple field , like I did in the screenshot above ?

**Comment by josegonzalez** [comment]
Sure that probably works.

**Comment by clementcrownrise** [comment]
![image](https://cloud.githubusercontent.com/assets/3583726/20851745/7fa78c28-b8e2-11e6-92c5-854cbf6cb982.png)


see my debug, the record is not added and no picture is uploaded

**Comment by clementcrownrise** [comment]
![image](https://cloud.githubusercontent.com/assets/3583726/20851792/bce80e6e-b8e2-11e6-80fd-ef24925478c6.png)

**Comment by josegonzalez** [comment]
@clementcrownrise please join the cakephp slack or irc room to get further support there.

**Comment by clementcrownrise** [comment]
Ok, thnks
