### ISSUE TITLE
Field 'photo_dir' doesn't have a default value

### ISSUE THREAD

**Issue by harshamv** [josegonzalez/cakephp-upload#421]
I am trying to set up an old cakePHP application in a new hosting and all of sudden am getting this error on the shared godaddy hosting. It works fine in the old hosting. Its been 2 years i have worked on CakePHP and dont seem to understand why this is coming. I am using the following upload plugin [cakephp-upload][1]

    Error: SQLSTATE[HY000]: General error: 1364 Field 'photo_dir' doesn't have a default value
    SQL Query: INSERT INTO `prayag_cms`.`galleries` (`branch_id`, `name`, `album_id`, `display_photo`, `modified`, `created`) VALUES (0, 'Photo', 1, 'CpLMQ28WYAEOnow.jpg_large.jpg', '2016-12-06 10:17:14', '2016-12-06 10:17:14')

This is my confirguration

    public $actsAs = array(
    			'Containable',
        'Upload.Upload' => array(
            'display_photo' => array(
                'fields' => array(
                    'dir' => 'photo_dir'
                ),
    							'thumbnailSizes' => array(
                    'small' => '250x250',
                ),
    							'thumbnailMethod' => 'php',
    							'path' => '{ROOT}webroot{DS}img{DS}{model}{DS}',
            ),
    
        )
    );

Controller:

    public function admin_add() {
    	if ($this->request->is('post')) {
    		$this->Gallery->create();
    		if ($this->Gallery->save($this->request->data)) {
    			$this->Session->setFlash(__('The gallery has been saved.'), 'admin/flash_success');
    			return $this->redirect(array('action' => 'index'));
    		} else {
    			$this->Session->setFlash(__('The gallery could not be saved. Please, try again.'), 'admin/flash_error');
    		}
    	}
    	$branches = $this->Gallery->Branch->find('list');
    	$albums = $this->Gallery->Album->find('list');
    	$this->set(compact('branches', 'albums'));
    }

  [1]: https://github.com/josegonzalez/cakephp-upload

**Comment by davidyell** [comment]
Do you have a `photo_dir` input in your views form?

**Comment by harshamv** [comment]
@davidyell until now it was taking the folder ID. it works perfectly in the localhost. no idea why this error all of sudden

**Comment by josegonzalez** [comment]
Check your table schemas locally and in production.

**Comment by hayatravis** [comment]
@davidyell
I am using 3.x, but a similar error occurred.
The cause was the setting of `php.ini`.
If uploading a file larger than the set value, the same error will occur.
Please check `post_max_size` and` upload_max_filesize` in `php.ini`.
I hope this will help you!

**Comment by Zwaen91** [comment]
@harshamv Have you solved this issue? I have the same problem. On my production webspace it is still working but not on my dev machine.

**Comment by harshamv** [comment]
@Zwaen91 nope was not able to
