### ISSUE TITLE
Uploading a video file

### ISSUE THREAD

**Issue by clementcrownrise** [josegonzalez/cakephp-upload#425]
Hi, I would like to upload three image file and one video file with your plugin, how can I go about it? If I upload images in the four file fields, it works perfectly , but any attempt to upload three images and one video, it gives error and nothing is uploaded.

How can I go about this? 

Thanks

**Comment by ADmad** [comment]
> .. it gives error ...

So what's the error?

**Comment by clementcrownrise** [comment]
It just said "unable to upload"

I guess i need to set that particular field to allow video format files.

**Comment by josegonzalez** [comment]
We don't block any files from being uploaded, so that is on you if you've done that. If you have not, it is likely that the file is too large to be uploaded.

**Comment by josegonzalez** [comment]
The error bubbles up to the validation layer, and I don't think we want to expose the server's max filesize limit.
