### ISSUE TITLE
Dynamic path

### ISSUE THREAD

**Issue by luisestudioalfa** [josegonzalez/cakephp-upload#429]
Hello everyone!

I have found several issues speaking of this but i can't make it work. I need to generate a dynamic path to save the file ( i also need to store this path in the database )

I would like to create a folder with the id of the user where the file will be saved.

for example:
`/images/21/imageavatar.jpg`

That would be the path for the user with id 21... Another user would have another different path...

So, i have tried to edit the config behaviour in the Model to add the 'path', but that creates a static path for all the users...

How can i create it dynamically? 

Continuing with the dynamic.... I algo want to sabe in the db the path that was generated, i'm using the 'nameCallback' to change the filename before saving it, but i do not know how to pass the previous generated path.

I'm sure you can tell but I'm pretty new to cake and i don't really know what i'm doing or how to do it....

Thanks in advance,
Luis.

**Comment by josegonzalez** [comment]
Can you show the code you used to configure the upload plugin?

**Comment by luisestudioalfa** [comment]
Sure. This is the code:

```
$this->addBehavior('Josegonzalez/Upload.Upload', [
  'img'=> [
    //'path' => '{DS}images{DS}application{DS}id_app{DS}features{DS}places{DS}',
    'fields' => [
        // if these fields or their defaults exist
        // the values will be set.
        'dir' => 'img_portada_dir', // defaults to `dir`
        'size' => 'img_portada_size', // defaults to `size`
        'type' => 'img_portada_type', // defaults to `type`
    ],				
    'nameCallback' => function(array $data, array $settings) {
        $ext = pathinfo($data['name'], PATHINFO_EXTENSION);
        $filename = pathinfo($data['name'], PATHINFO_FILENAME );
        return $filename.'-'.microtime().'.'.$ext; // added the microtime in case 2 files have the same name.
    },
    'transformer' => function (\Cake\Datasource\RepositoryInterface $table, \Cake\Datasource\EntityInterface $entity, $data, $field, $settings) {
        // get the extension from the file
        // there could be better ways to do this, and it will fail
        // if the file has no extension
        $extension = pathinfo($data['name'], PATHINFO_EXTENSION);
        // Store the thumbnail in a temporary file
        $tmp = tempnam(sys_get_temp_dir(), 'upload') . '.' . $extension;
        // Use the Imagine library to DO THE THING
        $size = new \Imagine\Image\Box(40, 40);
        $mode = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
        $imagine = new \Imagine\Gd\Imagine();
        // Save that modified file to our temp file
        $imagine->open($data['tmp_name'])
                ->thumbnail($size, $mode)
                ->save($tmp);
                // Now return the original *and* the thumbnail
                return [
                        $data['tmp_name'] => $data['name'],
                        $tmp => 'thumbnail-' . $data['name'],
                ];
        },
  ]
]);
```

I have commented the path option, if i don't all the images are saved on that path. 

What i don't know is how to pass parameters to the behaviour to change the path, name, or anything else dynamically... I found this code on the documentation, and i have modified it slightly...

Thanks.

**Comment by luisestudioalfa** [comment]
Ok. So i have solved it. What i had to do is to pass to the model the `id` of the user. and then change the path from what i had:

'path' => '{DS}images{DS}application{DS}features{DS}places{DS}'

to:

'path' => '{DS}images{DS}application{DS}'.user_id.'{DS}features{DS}places{DS}',

To get the user id, I used the session variable... I don't think its the best solution, but at least i can do it dynamically...

Thank you!
