### ISSUE TITLE
Thumbnail shell not working

### ISSUE THREAD

**Issue by golusin** [josegonzalez/cakephp-upload#432]
I'm trying to regenerate thumbnails for all the Product records. However, shell script doesn't do anything, apparently due to model naming problem. 

I'm using CakePHP 2.8.6 and here are two models related to this issue.

**Attachment**
```php
<?php
class Attachment extends AppModel {
  public $actsAs = array(
    'Upload.Upload' => array(
      'attachment' => array(
        'thumbnailMethod' => 'php',
        'thumbnailSizes' => array(
          'full' => '1024w',
          'large' => '800w',
          'medium' => '180x120',
          'thumb' => '100x100'
        ),
      )
    ),
  );

  public $belongsTo = array(
    'Product' => array(
      'className' => 'Product',
      'foreignKey' => 'foreign_key',
    )
  );
}
?>
```

and **Product**
```php
<?php
App::uses('AppModel', 'Model');

class Product extends AppModel {

  public $belongsTo = array(
    'User',
    'Category'
  );

  public $hasMany = array(
    'Image' => array(
      'className' => 'Attachment',
      'foreignKey' => 'foreign_key',
      'conditions' => array(
        'Image.model' => 'Product',
      ),
      'dependent' => true
    )
  );
?>
```

When I try to run shell script and put **Image** as model name, I get `Model 'Image' not found.` error message. However, when I put **Attachment** as model name, script fails to find the files. All the files are uploaded to `app/webroot/files/image/attachment/*`. When I output `$sourceFilePath` variable in `ThumbnailShell.php` shell script I can see that the script is looking for them at `app/webroot/files/attachment/attachment/*`.

Can anybody help me to resolve this one :(

**Comment by davidyell** [comment]
Sounds like a model alias issue to me. Although the file upload path doesn't seem logical to me either. I would have expected `webroot/files/attachment/<field>/<id>/<files>`

**Comment by golusin** [comment]
Yes, the path is exactly what you are expecting... `<field>` in Attachment model where the filename is stored is named **attachment**. 

I don't understand why shell script can't work with Image instead of Attachment when everything is working perfectly find when uploading files... all the records are created and files uploaded to `app/webroot/files/image/attachment/<id>/`

I'm not sure how to resolve this one :( Any ideas?

**Comment by davidyell** [comment]
Probably just needs a PR to use an `alias()` call on the Model.

Although [it does use `loadModel()`](https://github.com/josegonzalez/cakephp-upload/blob/2.x/Console/Command/ThumbnailShell.php#L37) so it should be taking care of aliases already.

**Comment by golusin** [comment]
It fails on [L43](https://github.com/josegonzalez/cakephp-upload/blob/2.x/Console/Command/ThumbnailShell.php#L43) and [L48](https://github.com/josegonzalez/cakephp-upload/blob/2.x/Console/Command/ThumbnailShell.php#L48). And if I comment out these two lines then I can see that the paths are wrong.

**Comment by davidyell** [comment]
Then it seems clear that your model class cannot be loaded and doesn't have the behaviour attached. Still seems like an issue with the class aliases to me.

**Comment by josegonzalez** [comment]
`loadModel` won't load the model from an association alias. You'll need to make a change to add alias support. I'll gladly accept a pull request, but as CakePHP 2.x is not the current stable version, I won't be fixing this in mainline on my own.
