### ISSUE TITLE
How to rename file ?

### ISSUE THREAD

**Issue by filipecamargo10** [josegonzalez/cakephp-upload#435]
Hi, i don't know how to rename the file to save.
Can you help me ?

**Comment by Spriz** [comment]
Did you see: https://github.com/josegonzalez/cakephp-upload/blob/21cef97798d82da9c31afdb3b1a246a453271665/docs/configuration.rst? :) It says something about renaming

**Comment by filipecamargo10** [comment]
I see, but i don't know how to use. Can u help me ? 
Look my example: 

`        $this->addBehavior('Josegonzalez/Upload.Upload', [
            'icon' => [
                'path' => 'webroot{DS}files{DS}{model}{DS}{field}{DS}',
            ]
        ]);`

The upload is correct, but ... when I upload a file with the same name it is overwritten.

**Comment by josegonzalez** [comment]
You need to specify the nameCallback option.

**Comment by filipecamargo10** [comment]
Fine. Can u give me a example ? It is a string or a function ?

**Comment by davidyell** [comment]
It is a method which the behavior can call.[ It's listed in the documentation](http://cakephp-upload.readthedocs.io/en/latest/configuration.html).

```php
public function renameFile(array $data, array $settings): string
{
    $newFilename = str_replace('Example', '', $data['file']);
    return $newFilename;
}
```
