### ISSUE TITLE
Auto-recreate thumbs via console, or ability to add new sizes and update the next time a record is saved

### ISSUE THREAD

**Issue by SouthWestMedia** [josegonzalez/cakephp-upload#79]
An excellent feature of the [Media Plugin](https://github.com/bmcclure/CakePHP-Media-Plugin) was the ability to recreate thumbnails via the console. This is especially helpful when you need to create a new thumbnail size on an existing application; which in the perfect world wouldn't happen, but can be necessary due to visual design changes etc. 

Currently I am unaware of any way to do this without having to add the new sizes and then reupload the image. 

An alternative would be perhaps an "Update thumbnails?" form check box, which, if ticked, would locate the original source image and regenerate the [new] thumbs.

I might be missing something in the plugin that offers a way to achieve this.

**Comment by davidyell** [comment]
Note to self, Needs documentation adding.

**Comment by davidyell** [comment]
Closing this issue in favour of the PR. #253
