### ISSUE TITLE
How to rename file name ?

### ISSUE THREAD

**Issue by hardiks** [josegonzalez/cakephp-upload#89]
I'm stuck at this point. I not getting which parameter I have to change to rename the file name.
I'm working on blog site on that I'm saving image's of user.And I want name of images like user's name following by serial number.

Thanks !

**Comment by tcdsMax** [comment]
Hi,
I post a modification I did in the Qimage file on one of my project, if someone still needs to easily rename a file. (I maybe forgot some testings but it's good enough for me ;-) )

Here is how the copy function looks like :

/**
 * Copy an uploaded image to the destination path
 *
 * $data['file'] 	-> array with image data (found in $_FILES)
 * $data['path'] 	-> destination path
 * $data['new_name']-> name of copied file
 *
 * @param array $data
 * @return mixed
 */
public function copy($data){
			
	// Verify file and path
	if (!isset($data['file']) || !isset($data['path']) || !is_array($data['file'])){
		$this->errors[] = 'Nom ou chemin introuvable !';
		return false;
	}

	if (!is_writable($data['path'])){
		$this->errors[] = 'Le dossier de destination est intedit en écriture !';
		return false;
	}
			
	if (!$this->_verifyMime($data['file']['name'])){
		$this->errors[] = 'Le fichier doit être une image jpg, gif ou png !';
		return false;
	}

	// Generate filename and move file to destination path
	if (!isset($data['new_name'])){
		$position_point 	= strrpos($data['file']['name'], '.');
		$filename 			= substr($data['file']['name'], 0, $position_point);
		$extension			= substr($data['file']['name'], -3);

		$image_name_slugged = strtolower(Inflector::slug($filename,'-'));
						
		//we build the name with the 'extension
		$name = $image_name_slugged . '.' . $extension;
			
	}else{
		$extension = substr($data['file']['name'], -3);
		$name = $data['new_name'] . '.' . $extension;
	}

	/we check if the the file already exists in the folder
	if ($folder = opendir($data['path'])){
		while (false !== ($file = readdir($folder))){
			if ($file == $name){
				$this->errors[] = "A file with this name already exists in the folder";
				return false;
			}
		}
        }

	$complete_path = $data['path'] . DIRECTORY_SEPARATOR . $name;

	if (!move_uploaded_file($data['file']['tmp_name'], $data['path'] . $name)){
		$this->errors[] = 'An error occured during the upload !';
			return false;
		}
			
		// Return image filename
		return $name;
			
	}
       
hope this helps, and josegonzalez great job with this component, very usefull ;-)
