### ISSUE TITLE
How to retrieve a file

### ISSUE THREAD

**Issue by ezequielp** [josegonzalez/cakephp-upload#95]
This may sound like a dumb question, but once I have a file uploaded is there a simple way of retrieving the full file path from the file id without having to reverse engineer it? 

I would expect something like: $this->FileModel->getPath($file_id);

At the moment, the only way of retrieving the file path requires knowledge of the inner working and configuration of the model/behaviour:

$file = 'hardcoded path root'.DS.'FileModel'.DS.$dir_as_stored_on_table.DS.$filename_as_stored_on_table

**Comment by eleiva** [comment]
+1

**Comment by davidyell** [comment]
You've configured the plugin, and you've stored the `dir` field of the file in your database. So from these things you can write a link to get the file.

I understand that you think it should be in the scope of the plugin, but it's something which is very simple to code yourself and as @josegonzalez has said, creating a 'one size fits all' for this would be very difficult.

**Comment by eleiva** [comment]
Well, So i'm missing something. 
Look at my current solution: 

```php
...
public static function getPictureUrl($creditCard) {
    return DS."files".DS."credit_card".DS.$creditCard['picture_dir'].DS.$creditCard['picture'];
  }
...
```
files and credit_card folder is hard coded now. 
I think it has to be managed by the plugin.
The plugin already know all of this.

Next i do in many pages :

```php
Router::url(CreditCard::getPictureUrl($creditCard))
```

Thanks!
