### ISSUE TITLE
Can't seem to get polymorphic working.

### ISSUE THREAD

**Issue by benjaminallison** [josegonzalez/cakephp-upload#98]
So, I made the db tables as shown. But when I save a model, attachments are not saved. It's almost like the plugin isn't getting called.

I've put the files in the right place, and have called it in Bootstrap.

Here's my Attachment model:

    public $actsAs = array(
        'Upload.Upload' => array(
            'attachment' => array(
                'fields' => array(
                    'dir' => 'photo_dir'
                ),
                'thumbnailMethod' => 'php',
                'thumbnailSizes' => array(
                    'large' => '1280x720',
                    'medium' => '960x540',
                    'small' => '640x360',
                    'thumb' => '200x200'
                )
            )
        )
    );

    public $belongsTo = array(
        'Burger' => array(
            'className' => 'Burger',
            'foreignKey' => 'foreign_key',
        )
    );

My Burger model (the one that Attachments are connected to):

    public $hasMany = array(
        'Attachment' => array(
            'className' => 'Attachment',
            'foreignKey' => 'foreign_key',
            'conditions' => array(
                'Attachment.model' => 'Burger',
            ),
        ),
    );

And the relevant parts of the view where files are attached:

    echo $this->Form->create('Burger', array('type' => 'file'));
    echo $this->Form->input('Attachment.attachment', array('type' => 'file', 'label' => false));
    echo $this->Form->end('Save Burger');

Not sure what I'm missing.

**Comment by josegonzalez** [comment]
Closing as there are now multiple examples.
